"use client";

import React from "react";
import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { clsx } from "clsx";
import { FileText, AlertTriangle, Scale, Ban, RefreshCw, Mail, ArrowRight } from "lucide-react";
import { Badge } from "@/components/ui/Badge";

const EASE_OUT: [number, number, number, number] = [0.22, 0.61, 0.36, 1];
const LAST_UPDATED = "April 8, 2026";

// ─── Shared prose helpers ─────────────────────────────────────────

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-foreground-muted leading-relaxed">{children}</p>;
}

function UL({ items }: { items: string[] }) {
  return (
    <ul className="list-disc list-inside space-y-1.5 pl-1">
      {items.map((item, i) => (
        <li key={i} className="text-foreground-muted">{item}</li>
      ))}
    </ul>
  );
}

function Prose({ children }: { children: React.ReactNode }) {
  return <div className="space-y-3 text-sm">{children}</div>;
}

// ─── TOC ─────────────────────────────────────────────────────────

const TOC_ITEMS = [
  { id: "acceptance",          label: "Acceptance of Terms"         },
  { id: "use-of-service",      label: "Use of Service"              },
  { id: "prohibited-conduct",  label: "Prohibited Conduct"          },
  { id: "intellectual-property", label: "Intellectual Property"     },
  { id: "disclaimers",         label: "Disclaimers"                 },
  { id: "limitation-liability",label: "Limitation of Liability"     },
  { id: "indemnification",     label: "Indemnification"             },
  { id: "termination",         label: "Termination"                 },
  { id: "governing-law",       label: "Governing Law"               },
  { id: "changes-to-terms",    label: "Changes to Terms"            },
  { id: "contact",             label: "Contact"                     },
];

interface TermsSection {
  id: string;
  title: string;
  icon: React.FC<{ className?: string }>;
  gradient: string;
  content: React.ReactNode;
}

const SECTIONS: TermsSection[] = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    icon: FileText,
    gradient: "from-violet-500 to-blue-500",
    content: (
      <Prose>
        <P>
          By accessing or using ToolHive (&ldquo;the Service&rdquo;), you agree to be bound
          by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms,
          please do not use the Service.
        </P>
        <P>
          These Terms apply to all visitors, registered users, and others who access
          or use the Service. Using the Service on behalf of a company or organisation
          means you represent that you have authority to bind that entity to these Terms.
        </P>
      </Prose>
    ),
  },
  {
    id: "use-of-service",
    title: "Use of Service",
    icon: FileText,
    gradient: "from-emerald-500 to-teal-400",
    content: (
      <Prose>
        <P>
          ToolHive grants you a limited, non-exclusive, non-transferable, revocable
          licence to access and use the Service for lawful purposes.
        </P>
        <p className="font-semibold text-foreground text-sm">You may:</p>
        <UL items={[
          "Use any tool on the platform for personal or commercial projects",
          "Process files you own or have the right to process",
          "Share output files generated by the Service",
        ]} />
        <p className="font-semibold text-foreground text-sm">You must:</p>
        <UL items={[
          "Comply with all applicable laws and regulations",
          "Respect the intellectual property rights of third parties",
          "Keep your account credentials secure and confidential",
        ]} />
      </Prose>
    ),
  },
  {
    id: "prohibited-conduct",
    title: "Prohibited Conduct",
    icon: Ban,
    gradient: "from-orange-400 to-rose-500",
    content: (
      <Prose>
        <P>You agree not to:</P>
        <UL items={[
          "Upload, process, or distribute illegal, harmful, or infringing content",
          "Attempt to reverse-engineer, decompile, or extract source code from the Service",
          "Use automated tools (bots, scrapers) to access the Service at scale without written permission",
          "Circumvent, disable, or interfere with security features",
          "Attempt to gain unauthorised access to any part of the Service or its infrastructure",
          "Use the Service to send spam, phishing content, or other unsolicited communications",
          "Impersonate ToolHive or any other person or entity",
          "Process files containing CSAM or any material that sexualises minors",
        ]} />
        <P>
          Violation of these prohibitions may result in immediate account termination
          and, where appropriate, referral to law enforcement.
        </P>
      </Prose>
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    icon: Scale,
    gradient: "from-sky-500 to-cyan-400",
    content: (
      <Prose>
        <P>
          The Service, including its design, code, branding, and content, is owned
          by ToolHive Inc. and protected by copyright, trademark, and other intellectual
          property laws.
        </P>
        <P>
          <strong className="text-foreground">Your content:</strong> You retain all
          rights to files you upload. By using the Service you grant ToolHive a
          temporary, limited licence to process your files solely to provide the
          requested operation. This licence terminates as soon as processing is complete.
        </P>
        <P>
          <strong className="text-foreground">Output files:</strong> Files generated
          by the Service are yours. ToolHive claims no ownership over the output of
          any processing operation.
        </P>
      </Prose>
    ),
  },
  {
    id: "disclaimers",
    title: "Disclaimers",
    icon: AlertTriangle,
    gradient: "from-orange-400 to-rose-500",
    content: (
      <Prose>
        <P>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES
          OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        </P>
        <P>
          ToolHive does not warrant that the Service will be uninterrupted, error-free,
          or free of viruses or other harmful components. You use the Service at your
          own risk.
        </P>
        <P>
          AI-generated outputs may contain errors or inaccuracies. Always review AI
          output before relying on it for important decisions.
        </P>
      </Prose>
    ),
  },
  {
    id: "limitation-liability",
    title: "Limitation of Liability",
    icon: Scale,
    gradient: "from-violet-500 to-blue-500",
    content: (
      <Prose>
        <P>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, TOOLHIVE AND ITS OFFICERS, DIRECTORS,
          EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF DATA, PROFITS, OR GOODWILL,
          ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.
        </P>
        <P>
          OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING OUT OF THESE TERMS OR THE
          SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE
          12 MONTHS PRECEDING THE CLAIM OR (B) USD $100.
        </P>
      </Prose>
    ),
  },
  {
    id: "indemnification",
    title: "Indemnification",
    icon: Scale,
    gradient: "from-emerald-500 to-teal-400",
    content: (
      <Prose>
        <P>
          You agree to indemnify, defend, and hold harmless ToolHive Inc. and its
          affiliates, officers, directors, employees, and agents from and against any
          claims, liabilities, damages, losses, and expenses (including reasonable
          legal fees) arising out of or in any way connected with:
        </P>
        <UL items={[
          "Your use of or inability to use the Service",
          "Your violation of these Terms",
          "Your violation of any third-party rights, including intellectual property rights",
          "Any content you upload, process, or transmit through the Service",
        ]} />
      </Prose>
    ),
  },
  {
    id: "termination",
    title: "Termination",
    icon: Ban,
    gradient: "from-sky-500 to-cyan-400",
    content: (
      <Prose>
        <P>
          We reserve the right to suspend or terminate your access to the Service at
          any time, with or without notice, for any reason, including if we reasonably
          believe you have violated these Terms.
        </P>
        <P>
          You may delete your account at any time from{" "}
          <Link href="/dashboard/settings" className="text-violet-500 hover:underline">
            Dashboard → Settings
          </Link>
          . Termination does not relieve you of obligations incurred prior to termination.
        </P>
        <P>
          Provisions that by their nature should survive termination (including
          intellectual property, disclaimers, limitation of liability, and
          governing law) will survive.
        </P>
      </Prose>
    ),
  },
  {
    id: "governing-law",
    title: "Governing Law",
    icon: Scale,
    gradient: "from-violet-500 to-blue-500",
    content: (
      <Prose>
        <P>
          These Terms are governed by and construed in accordance with the laws of
          the State of California, USA, without regard to its conflict-of-law principles.
        </P>
        <P>
          Any dispute arising out of or relating to these Terms shall be resolved by
          binding arbitration in San Francisco, California, except that either party
          may seek injunctive relief in a court of competent jurisdiction.
        </P>
      </Prose>
    ),
  },
  {
    id: "changes-to-terms",
    title: "Changes to Terms",
    icon: RefreshCw,
    gradient: "from-orange-400 to-rose-500",
    content: (
      <Prose>
        <P>
          We may revise these Terms from time to time. When we make material changes,
          we will notify registered users via email and update the &ldquo;Last updated&rdquo;
          date. Continued use of the Service after changes take effect constitutes
          your acceptance of the revised Terms.
        </P>
      </Prose>
    ),
  },
  {
    id: "contact",
    title: "Contact",
    icon: Mail,
    gradient: "from-violet-500 to-cyan-500",
    content: (
      <Prose>
        <P>
          For questions about these Terms, please contact us:
        </P>
        <UL items={[
          "Email: legal@toolhive.app",
          "Postal: ToolHive Inc., 123 Mission Street, San Francisco, CA 94105, USA",
        ]} />
      </Prose>
    ),
  },
];

// ─── Card ─────────────────────────────────────────────────────────

function SectionCard({
  section,
  shouldReduce,
  index,
}: {
  section: TermsSection;
  shouldReduce: boolean;
  index: number;
}) {
  const Icon = section.icon;
  return (
    <motion.div
      id={section.id}
      initial={shouldReduce ? undefined : { opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-40px" }}
      transition={{ duration: 0.5, delay: index * 0.03, ease: EASE_OUT }}
      className="border border-card-border bg-card rounded-2xl p-6 sm:p-8 scroll-mt-24"
    >
      <div className="flex items-start gap-4 mb-5">
        <div
          className={clsx(
            "flex h-10 w-10 shrink-0 items-center justify-center rounded-xl",
            `bg-gradient-to-br ${section.gradient}`,
            "shadow-md"
          )}
          aria-hidden="true"
        >
          <Icon className="h-5 w-5 text-white" />
        </div>
        <h2 className="text-lg sm:text-xl font-bold text-foreground leading-snug pt-0.5">
          {section.title}
        </h2>
      </div>
      {section.content}
    </motion.div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────

export function TermsOfServicePage() {
  const shouldReduce = useReducedMotion() ?? false;

  return (
    <>
      {/* Hero */}
      <section className="relative isolate overflow-hidden pt-20 pb-12 sm:pt-28 sm:pb-16">
        <div className="absolute inset-0 -z-10">
          <div className="absolute inset-0 bg-background" />
          <div
            className="absolute -top-40 right-0 h-[520px] w-[520px] rounded-full"
            style={{ background: "radial-gradient(circle, oklch(55% 0.22 285 / 0.08) 0%, transparent 70%)" }}
          />
        </div>
        <div className="container mx-auto px-4">
          <motion.div
            initial={shouldReduce ? undefined : { opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: EASE_OUT }}
            className="max-w-3xl"
          >
            <Badge variant="primary" size="md" className="mb-4">Legal</Badge>
            <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-foreground leading-[1.08] mb-4">
              Terms of Service
            </h1>
            <p className="text-base sm:text-lg text-foreground-muted leading-relaxed max-w-2xl mb-4">
              Please read these terms carefully before using ToolHive. By using our
              platform you agree to be bound by them.
            </p>
            <p className="text-sm text-foreground-muted">
              Last updated: <span className="font-semibold text-foreground">{LAST_UPDATED}</span>
            </p>
          </motion.div>
        </div>
      </section>

      {/* Body */}
      <section className="pb-20 sm:pb-28">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-8 lg:gap-12 max-w-5xl mx-auto">
            {/* Sticky TOC */}
            <aside className="hidden lg:block">
              <div className="sticky top-24">
                <p className="text-xs font-semibold uppercase tracking-widest text-foreground-muted mb-3">
                  Contents
                </p>
                <nav aria-label="Terms sections">
                  <ul className="space-y-1">
                    {TOC_ITEMS.map((item) => (
                      <li key={item.id}>
                        <a
                          href={`#${item.id}`}
                          className={clsx(
                            "block text-sm text-foreground-muted hover:text-foreground",
                            "py-1 px-2 rounded-lg hover:bg-background-subtle",
                            "transition-colors duration-150"
                          )}
                        >
                          {item.label}
                        </a>
                      </li>
                    ))}
                  </ul>
                </nav>
              </div>
            </aside>

            {/* Sections */}
            <div className="space-y-4">
              {SECTIONS.map((section, index) => (
                <SectionCard
                  key={section.id}
                  section={section}
                  shouldReduce={shouldReduce}
                  index={index}
                />
              ))}

              {/* CTA */}
              <motion.div
                initial={shouldReduce ? undefined : { opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, ease: EASE_OUT }}
                className="rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-500 p-6 sm:p-8 text-white"
              >
                <h3 className="text-lg font-bold mb-2">Questions about our Terms?</h3>
                <p className="text-white/80 text-sm mb-4">
                  Our team is happy to clarify anything in this document.
                </p>
                <Link
                  href="/contact"
                  className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-2.5 text-sm font-bold text-violet-600 hover:bg-white/90 transition-colors"
                >
                  Get in Touch
                  <ArrowRight className="h-4 w-4" aria-hidden="true" />
                </Link>
              </motion.div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
