import type { NavItem } from "@/types";

/**
 * Top-level nav links for the Navbar.
 * Keep this list short (5 max) — secondary links live in the sidebar/footer.
 */
export const NAV_LINKS: NavItem[] = [
  { label: "PDF Tools", href: "/tools/pdf" },
  { label: "Image Tools", href: "/tools/image" },
  { label: "AI Writing", href: "/tools/ai-writing" },
  { label: "Calculators", href: "/tools/calculator" },
  { label: "Instagram Automation", href: "/instagram-automation" },
  { label: "All Tools", href: "/tools" },
];

/**
 * Category config used in the mobile menu and category grid.
 * icon is a string emoji for simplicity — components render lucide icons
 * by looking up the `iconName` field.
 */
export const TOOL_CATEGORIES = [
  {
    id: "pdf",
    label: "PDF Tools",
    description: "Compress, merge, split, convert, and sign PDF files.",
    icon: "📄",
    iconName: "FileText",
    color: "rose",
    gradient: "from-rose-500 to-orange-400",
    toolCount: 26,
    href: "/tools/pdf",
  },
  {
    id: "image",
    label: "Image Tools",
    description: "Resize, compress, convert, and enhance images with AI.",
    icon: "🖼️",
    iconName: "Image",
    color: "violet",
    gradient: "from-violet-500 to-purple-400",
    toolCount: 57,
    href: "/tools/image",
  },
  {
    id: "video",
    label: "Video Downloader",
    description: "Download videos from YouTube, Instagram, TikTok, Facebook, Twitter/X, and Vimeo in HD.",
    icon: "🎬",
    iconName: "Video",
    color: "blue",
    gradient: "from-blue-500 to-cyan-400",
    toolCount: 6,
    href: "/tools/video/youtube",
  },
  {
    id: "ai-writing",
    label: "AI Writing",
    description: "Rewrite, summarize, translate, and improve any text with AI.",
    icon: "✍️",
    iconName: "Pen",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-400",
    toolCount: 39,
    href: "/tools/ai-writing",
  },
  {
    id: "converter",
    label: "Converter",
    description: "Currency, timezone, code formatter, diff checker, regex, fancy text, TTS, hash, morse — 25+ tools.",
    icon: "🔄",
    iconName: "ArrowRightLeft",
    color: "sky",
    gradient: "from-sky-500 to-indigo-400",
    toolCount: 31,
    href: "/tools/converter",
  },
  {
    id: "resume",
    label: "Resume Tools",
    description: "Build, analyze, and optimize professional resumes with AI.",
    icon: "📋",
    iconName: "FileText",
    color: "indigo",
    gradient: "from-indigo-500 to-purple-600",
    toolCount: 12,
    href: "/tools/resume",
  },
  {
    id: "calculator",
    label: "Calculators",
    description: "EMI, SIP, GST, Income Tax, FD, Scientific, Calorie, Tip, Discount — 28 practical calculators.",
    icon: "🧮",
    iconName: "Calculator",
    color: "orange",
    gradient: "from-orange-500 to-amber-400",
    toolCount: 28,
    href: "/tools/calculator",
  },
  {
    id: "contact-creator",
    label: "Contact & Creator",
    description: "Link in bio, social bios, auto-reply templates, email signatures, WhatsApp links, vCards and more.",
    icon: "📱",
    iconName: "Smartphone",
    color: "pink",
    gradient: "from-pink-500 to-rose-400",
    toolCount: 12,
    href: "/tools/contact-creator",
  },
  {
    id: "social-media",
    label: "Social Media",
    description: "Hashtag analyzer, bio generator, caption formatter, post scheduler, meme tools and more.",
    icon: "📣",
    iconName: "Share2",
    color: "purple",
    gradient: "from-purple-500 to-pink-400",
    toolCount: 14,
    href: "/tools/social-media",
  },
  {
    id: "generators",
    label: "Generators",
    description: "Random password, UUID, barcode, QR code, fake address, story ideas, name generators and more.",
    icon: "🎲",
    iconName: "Sparkles",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-400",
    toolCount: 137,
    href: "/tools/generators",
  },
  {
    id: "text-writing",
    label: "Text & Writing",
    description: "Word counter, character counter, case converter, lorem ipsum, text diff checker, grammar checker and more.",
    icon: "✏️",
    iconName: "PenLine",
    color: "teal",
    gradient: "from-teal-500 to-green-400",
    toolCount: 71,
    href: "/tools/text-writing",
  },
  {
    id: "utilities",
    label: "Utilities",
    description: "Battery estimator, internet speed test, countdown timer, stopwatch, QR scanner, URL shortener and more.",
    icon: "🔧",
    iconName: "Wrench",
    color: "gray",
    gradient: "from-gray-600 to-slate-500",
    toolCount: 29,
    href: "/tools/utilities",
  },
  {
    id: "device",
    label: "Device & Utility",
    description: "IP lookup, Whois, subnet calculator, ping tool, trace route, file hash, clipboard manager and more.",
    icon: "🖥️",
    iconName: "Monitor",
    color: "slate",
    gradient: "from-slate-600 to-zinc-500",
    toolCount: 11,
    href: "/tools/device",
  },
  {
    id: "finance",
    label: "Finance & Business",
    description: "Invoice generator, ROI calculator, profit margin, startup valuation, capital gains, expense tracker and more.",
    icon: "💰",
    iconName: "DollarSign",
    color: "green",
    gradient: "from-green-600 to-emerald-500",
    toolCount: 18,
    href: "/tools/finance",
  },
  {
    id: "productivity",
    label: "Productivity",
    description: "Daily planner, weekly planner, meeting minutes, task checklist, content calendar, packing list and more.",
    icon: "🚀",
    iconName: "Zap",
    color: "amber",
    gradient: "from-amber-500 to-yellow-400",
    toolCount: 21,
    href: "/tools/productivity",
  },
  {
    id: "code",
    label: "Code & Dev",
    description: "CSS gradient, JS array, SQL generator, HTML table, box shadow, browser info, cache cleaner and more.",
    icon: "💻",
    iconName: "Code",
    color: "blue",
    gradient: "from-blue-600 to-indigo-500",
    toolCount: 23,
    href: "/tools/code",
  },
  {
    id: "seo",
    label: "SEO & Web",
    description: "Meta description, structured data, sitemap validator, regex, JS date formatter, HTML canvas and more.",
    icon: "🔍",
    iconName: "Search",
    color: "violet",
    gradient: "from-violet-600 to-purple-500",
    toolCount: 22,
    href: "/tools/seo",
  },
  {
    id: "education",
    label: "Education & Learning",
    description: "Flashcards, quiz maker, vocabulary builder, study planner, timeline generator, trivia and more.",
    icon: "🎓",
    iconName: "GraduationCap",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-500",
    toolCount: 28,
    href: "/tools/education",
  },
  {
    id: "health",
    label: "Health & Fitness",
    description: "BMI, calorie calculator, workout generator, calorie deficit, VO2 max, sleep debt, pregnancy calculators and more.",
    icon: "❤️",
    iconName: "Heart",
    color: "red",
    gradient: "from-red-500 to-pink-500",
    toolCount: 17,
    href: "/tools/health",
  },
  {
    id: "travel",
    label: "Travel & Location",
    description: "Trip distance, travel insurance, packing list, timezone converter, hotel comparison and more.",
    icon: "✈️",
    iconName: "Plane",
    color: "sky",
    gradient: "from-sky-500 to-cyan-400",
    toolCount: 16,
    href: "/tools/travel",
  },
  {
    id: "entertainment",
    label: "Entertainment & Fun",
    description: "Meme generator, movie plot generator, D&D character, RPG character, trivia quiz, daily affirmations and more.",
    icon: "🎮",
    iconName: "Gamepad2",
    color: "fuchsia",
    gradient: "from-fuchsia-500 to-pink-400",
    toolCount: 10,
    href: "/tools/entertainment",
  },
] as const;

export type ToolCategoryConfig = (typeof TOOL_CATEGORIES)[number];
