import type { Tool, ToolCategory } from "@/types";

// ─────────────────────────────────────────────
// Tool registry
// In production this comes from a database/CMS.
// This file is the static type-safe fallback and
// source of truth for generateStaticParams.
// ─────────────────────────────────────────────

export const TOOLS: Tool[] = [
  // ── PDF Tools ──────────────────────────────
  {
    id: "pdf-compress",
    slug: "compress",
    name: "Compress PDF",
    description:
      "Reduce PDF file size while maintaining quality. Supports batch compression of multiple files at once with smart optimization.",
    shortDescription: "Reduce PDF file size without losing quality.",
    category: "pdf",
    icon: "FileDown",
    tags: ["compress", "optimize", "reduce size"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_400_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 20,
  },
  {
    id: "pdf-merge",
    slug: "merge",
    name: "Merge PDF",
    description:
      "Combine multiple PDF files into one. Drag to reorder pages before merging for precise document control.",
    shortDescription: "Combine multiple PDFs into one document.",
    category: "pdf",
    icon: "Combine",
    tags: ["merge", "combine", "join"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_800_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 50,
  },
  {
    id: "pdf-split",
    slug: "split",
    name: "Split PDF",
    description: "Split a PDF into individual pages or custom page ranges. Extract exactly what you need.",
    shortDescription: "Split PDF into individual pages or ranges.",
    category: "pdf",
    icon: "Scissors",
    tags: ["split", "separate", "extract pages"],
    usageCount: 980_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-to-word",
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF documents to editable Word (.docx) files with AI-powered layout preservation.",
    shortDescription: "Convert PDF to editable Word document.",
    category: "pdf",
    icon: "FileEdit",
    tags: ["convert", "word", "docx", "editable"],
    isNew: true,
    isFeatured: true,
    usageCount: 650_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },
  {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert each PDF page into high-quality JPG images. Choose resolution and quality settings.",
    shortDescription: "Convert PDF pages to JPG images.",
    category: "pdf",
    icon: "Image",
    tags: ["convert", "jpg", "image", "export"],
    usageCount: 870_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 10,
  },
  {
    id: "pdf-rotate",
    slug: "rotate",
    name: "Rotate PDF",
    description: "Rotate individual pages or the entire PDF document. Fix incorrectly scanned documents in seconds.",
    shortDescription: "Rotate PDF pages to correct orientation.",
    category: "pdf",
    icon: "RotateCw",
    tags: ["rotate", "orientation", "fix"],
    usageCount: 420_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },

  // ── Image Tools ─────────────────────────────
  {
    id: "image-compress",
    slug: "compress",
    name: "Compress Image",
    description: "Compress JPEG, PNG, WebP images up to 90% smaller with no visible quality loss using smart AI compression.",
    shortDescription: "Compress images without visible quality loss.",
    category: "image",
    icon: "ImageDown",
    tags: ["compress", "optimize", "reduce size"],
    isPopular: true,
    isFeatured: true,
    usageCount: 3_200_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
    maxFileSizeMB: 25,
    maxFiles: 30,
  },
  {
    id: "image-resize",
    slug: "resize",
    name: "Resize Image",
    description: "Resize images to exact pixel dimensions or percentage. Maintain aspect ratio with smart crop options.",
    shortDescription: "Resize images to any dimension.",
    category: "image",
    icon: "Scaling",
    tags: ["resize", "dimensions", "scale"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_500_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-bg-remove",
    slug: "remove-background",
    name: "Remove Background",
    description: "AI-powered background removal. Get transparent PNG in seconds. Perfect for product photos and portraits.",
    shortDescription: "Remove image background with AI instantly.",
    category: "image",
    icon: "Eraser",
    tags: ["background removal", "transparent", "AI"],
    isNew: true,
    isFeatured: true,
    usageCount: 2_100_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 10,
    maxFiles: 5,
  },
  {
    id: "image-convert",
    slug: "convert",
    name: "Convert Image",
    description: "Convert between JPG, PNG, WebP, AVIF, GIF and more. Batch convert hundreds of images at once.",
    shortDescription: "Convert between all image formats.",
    category: "image",
    icon: "ArrowRightLeft",
    tags: ["convert", "format", "jpg", "png", "webp"],
    usageCount: 780_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp", ".tiff"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },

  // ── Video Tools ─────────────────────────────
  {
    id: "video-compress",
    slug: "compress",
    name: "Compress Video",
    description: "Reduce video file size with minimal quality loss. Supports MP4, MOV, AVI, WebM with H.264/H.265 encoding.",
    shortDescription: "Compress video files without quality loss.",
    category: "video",
    icon: "VideoOff",
    tags: ["compress", "reduce size", "MP4"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_200_000,
    estimatedTime: "~30s",
    acceptedFileTypes: [".mp4", ".mov", ".avi", ".webm", ".mkv"],
    maxFileSizeMB: 500,
    maxFiles: 3,
  },
  // ── AI Writing ──────────────────────────────
  {
    id: "ai-summarize",
    slug: "summarize",
    name: "AI Summarizer",
    description: "Summarize long articles, documents, or text into clear bullet points or concise paragraphs with one click.",
    shortDescription: "Summarize any text with AI in seconds.",
    category: "ai-writing",
    icon: "AlignLeft",
    tags: ["summarize", "condense", "abstract"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_600_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-translate",
    slug: "translate",
    name: "AI Translator",
    description: "Translate text between 100+ languages with context-aware AI translation that preserves tone and meaning.",
    shortDescription: "Translate text into 100+ languages.",
    category: "ai-writing",
    icon: "Languages",
    tags: ["translate", "language", "localize"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_300_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-rewrite",
    slug: "rewrite",
    name: "AI Rewriter",
    description: "Rewrite any text to improve clarity, tone, or style. Choose from professional, casual, formal, or creative modes.",
    shortDescription: "Rewrite text to improve clarity and tone.",
    category: "ai-writing",
    icon: "RefreshCw",
    tags: ["rewrite", "paraphrase", "rephrase"],
    isNew: true,
    usageCount: 740_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-grammar",
    slug: "grammar-check",
    name: "Grammar Checker",
    description: "Fix grammar, spelling, and punctuation errors instantly. Get detailed explanations for every correction made.",
    shortDescription: "Check and fix grammar errors with AI.",
    category: "ai-writing",
    icon: "SpellCheck",
    tags: ["grammar", "spell check", "proofread"],
    usageCount: 1_100_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── More PDF Tools ──────────────────────────
  {
    id: "pdf-unlock",
    slug: "unlock",
    name: "Unlock PDF",
    description: "Remove password protection from PDF files. Instantly unlock encrypted PDFs for editing and printing.",
    shortDescription: "Remove password protection from PDF.",
    category: "pdf",
    icon: "LockOpen",
    tags: ["unlock", "password", "remove protection"],
    isNew: true,
    usageCount: 430_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 5,
  },
  {
    id: "pdf-protect",
    slug: "protect",
    name: "Protect PDF",
    description: "Add password protection to PDF files. Set open password and permission restrictions to secure sensitive documents.",
    shortDescription: "Add password protection to PDF.",
    category: "pdf",
    icon: "Lock",
    tags: ["protect", "password", "secure", "encrypt"],
    usageCount: 280_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 5,
  },
  {
    id: "pdf-watermark",
    slug: "watermark",
    name: "Add Watermark",
    description: "Add text or image watermarks to PDF documents. Customize position, opacity, font, and color.",
    shortDescription: "Add watermark text or logo to PDF.",
    category: "pdf",
    icon: "Stamp",
    tags: ["watermark", "stamp", "brand", "protect"],
    usageCount: 310_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 10,
  },
  {
    id: "pdf-to-excel",
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Convert PDF tables and data into editable Excel spreadsheets (.xlsx) with AI-powered table detection.",
    shortDescription: "Convert PDF tables to Excel spreadsheet.",
    category: "pdf",
    icon: "TableProperties",
    tags: ["convert", "excel", "xlsx", "table"],
    isNew: true,
    usageCount: 520_000,
    estimatedTime: "~12s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },
  {
    id: "pdf-sign",
    slug: "sign",
    name: "Sign PDF",
    description: "Add digital signatures to PDF files. Draw, type, or upload your signature and place it anywhere.",
    shortDescription: "Add digital signature to PDF.",
    category: "pdf",
    icon: "PenLine",
    tags: ["sign", "signature", "esign", "digital"],
    isFeatured: true,
    isNew: true,
    usageCount: 680_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 1,
  },
  {
    id: "pdf-page-numbers",
    slug: "page-numbers",
    name: "Add Page Numbers",
    description: "Add customizable page numbers to PDF documents. Choose position, font, size, start number, and format.",
    shortDescription: "Add page numbers to PDF documents.",
    category: "pdf",
    icon: "Hash",
    tags: ["page numbers", "numbering", "footer", "header"],
    usageCount: 190_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-ocr",
    slug: "ocr",
    name: "PDF OCR",
    description: "Extract text from scanned PDFs and images using AI-powered OCR. Converts scanned documents into searchable, editable text. Supports 40+ languages.",
    shortDescription: "Extract text from scanned PDFs with OCR.",
    category: "pdf",
    icon: "ScanText",
    tags: ["ocr", "scan", "extract text", "scanned", "searchable"],
    isNew: true,
    isFeatured: true,
    usageCount: 390_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".pdf", ".jpg", ".jpeg", ".png", ".tiff"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },

  {
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG, PNG, or WebP images to a single PDF. Drag to reorder, choose page size and margins.",
    shortDescription: "Convert images to a PDF document.",
    category: "pdf",
    icon: "FileImage",
    tags: ["jpg", "image", "convert", "create pdf"],
    isPopular: true,
    usageCount: 1_100_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 50,
  },

  // ── More Image Tools ─────────────────────────
  {
    id: "image-thumbnail-creator",
    slug: "thumbnail-creator",
    name: "AI Thumbnail Creator",
    description: "Describe your thumbnail idea and AI generates it instantly. Upload your own photo to include yourself in the thumbnail. Supports YouTube, Instagram, Twitter/X, and more.",
    shortDescription: "Describe your idea, AI creates your thumbnail.",
    category: "image",
    icon: "Sparkles",
    tags: ["thumbnail", "ai", "youtube", "instagram", "generate", "design"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 850_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 10,
    maxFiles: 1,
    howItWorks: [
      { title: "Describe your thumbnail", description: "Type what you want — e.g. 'Gaming thumbnail with fire effects and my photo in the corner'. The more detail, the better." },
      { title: "Upload your photo (optional)", description: "Drop in your own photo and it will be layered into the generated thumbnail automatically." },
      { title: "Generate & download", description: "Click Generate to create your thumbnail. Adjust style, text, and colors, then download in full resolution." },
    ],
  },
  {
    id: "image-crop",
    slug: "crop",
    name: "Crop Image",
    description: "Crop images to exact dimensions or aspect ratios. Supports free crop, fixed ratios (1:1, 16:9, 4:3), and custom pixel crops.",
    shortDescription: "Crop images to any size or ratio.",
    category: "image",
    icon: "Crop",
    tags: ["crop", "trim", "resize", "aspect ratio"],
    isPopular: true,
    usageCount: 1_200_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-watermark",
    slug: "watermark",
    name: "Image Watermark",
    description: "Add text or logo watermarks to images. Customize opacity, position, size, and font. Batch process multiple images.",
    shortDescription: "Add text or logo watermark to images.",
    category: "image",
    icon: "Stamp",
    tags: ["watermark", "logo", "brand", "protect"],
    usageCount: 390_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-to-pdf",
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert one or multiple images to a single PDF file. Supports JPG, PNG, WebP. Customize page size and margins.",
    shortDescription: "Convert images to PDF in one click.",
    category: "image",
    icon: "FilePlus",
    tags: ["convert", "pdf", "jpg", "png"],
    usageCount: 720_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 50,
    maxFiles: 30,
  },
  {
    id: "qr-code-generator",
    slug: "qr-code",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, Wi-Fi, vCard, and more. Customize colors, size, and download as PNG or SVG.",
    shortDescription: "Generate custom QR codes instantly.",
    category: "image",
    icon: "QrCode",
    tags: ["qr code", "generator", "url", "barcode"],
    isNew: true,
    isFeatured: true,
    usageCount: 1_400_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "image-upscale",
    slug: "upscale",
    name: "AI Image Upscaler",
    description: "Upscale images 2x or 4x using AI super-resolution. Enhances details and sharpness without pixelation.",
    shortDescription: "Upscale images 2x–4x with AI.",
    category: "image",
    icon: "Maximize2",
    tags: ["upscale", "enhance", "AI", "resolution", "super resolution"],
    isFeatured: true,
    isNew: true,
    usageCount: 960_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 10,
    maxFiles: 5,
  },
  {
    id: "meme-generator",
    slug: "meme",
    name: "Meme Generator",
    description: "Create memes with popular templates or upload your own image. Add top and bottom text with custom fonts and colors.",
    shortDescription: "Create memes with templates or custom images.",
    category: "image",
    icon: "Smile",
    tags: ["meme", "fun", "text", "social media"],
    isNew: true,
    usageCount: 450_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },

  // ── Image Effects (new) ────────────────────
  {
    id: "image-black-white",
    slug: "black-white",
    name: "Photo Black & White",
    shortDescription: "Convert any photo to black & white instantly.",
    description: "Convert photos to stunning black and white with adjustable contrast and brightness controls.",
    category: "image",
    icon: "Circle",
    tags: ["black white", "grayscale", "monochrome", "filter"],
    usageCount: 890_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-pixelate",
    slug: "pixelate",
    name: "Pixelate Image",
    shortDescription: "Pixelate or censor parts of an image with a brush.",
    description: "Paint over areas to pixelate or blur for privacy, artistic effects, or censoring sensitive content.",
    category: "image",
    icon: "Grid3x3",
    tags: ["pixelate", "censor", "privacy", "blur"],
    usageCount: 320_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-blur-bg",
    slug: "blur-background",
    name: "Blur Background",
    shortDescription: "Blur the background of any photo automatically.",
    description: "Create stunning portrait-mode blur effects by automatically detecting and blurring the background.",
    category: "image",
    icon: "Blend",
    tags: ["blur", "background", "portrait", "bokeh"],
    usageCount: 680_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 5,
  },
  {
    id: "image-cleanup",
    slug: "cleanup",
    name: "Cleanup Picture",
    shortDescription: "Remove unwanted objects from photos with a brush.",
    description: "Paint over any object with a brush to remove it. Perfect for removing blemishes, objects, and distractions from photos.",
    category: "image",
    icon: "Eraser",
    tags: ["cleanup", "remove objects", "inpaint", "retouch"],
    isNew: true,
    isFeatured: true,
    usageCount: 760_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-flip",
    slug: "flip",
    name: "Image Flipper",
    shortDescription: "Flip or mirror images horizontally or vertically.",
    description: "Instantly flip or mirror images horizontally (left-right) or vertically (top-bottom).",
    category: "image",
    icon: "FlipHorizontal",
    tags: ["flip", "mirror", "horizontal", "vertical"],
    usageCount: 440_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-add-border",
    slug: "add-border",
    name: "Add Border to Image",
    shortDescription: "Add a custom border or frame to any image.",
    description: "Add custom colored borders and frames to images. Choose border width, color, and style.",
    category: "image",
    icon: "Square",
    tags: ["border", "frame", "edge", "decorate"],
    usageCount: 280_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-round",
    slug: "round-image",
    name: "Make Image Round",
    shortDescription: "Crop images into circle or rounded shapes.",
    description: "Convert any image into a perfect circle or rounded rectangle. Great for profile photos and logos.",
    category: "image",
    icon: "CircleDot",
    tags: ["round", "circle", "crop", "profile photo"],
    usageCount: 390_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-combine",
    slug: "combine",
    name: "Combine Images",
    shortDescription: "Combine multiple images side by side or in a grid.",
    description: "Merge multiple images into one. Choose side-by-side, grid, or vertical layouts with custom spacing.",
    category: "image",
    icon: "LayoutGrid",
    tags: ["combine", "merge", "collage", "layout"],
    usageCount: 340_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 50,
    maxFiles: 20,
  },
  {
    id: "image-profile-photo",
    slug: "profile-photo",
    name: "Profile Photo Maker",
    shortDescription: "Create the perfect profile photo for social media.",
    description: "Crop, resize, and optimize photos for LinkedIn, Instagram, Twitter, and other platforms.",
    category: "image",
    icon: "UserCircle",
    tags: ["profile photo", "avatar", "social media", "crop"],
    usageCount: 520_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 5,
  },
  {
    id: "image-remove-watermark",
    slug: "remove-watermark",
    name: "Remove Watermark",
    shortDescription: "Remove watermarks from images with AI.",
    description: "Automatically detect and remove watermarks, logos, and text overlays from images using AI inpainting.",
    category: "image",
    icon: "Stamp",
    tags: ["watermark", "remove", "clean", "AI"],
    usageCount: 470_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 5,
  },
  {
    id: "image-collage",
    slug: "collage",
    name: "Collage Maker",
    shortDescription: "Create beautiful photo collages with templates.",
    description: "Create stunning photo collages using beautiful templates. Drag and arrange photos with custom backgrounds.",
    category: "image",
    icon: "LayoutTemplate",
    tags: ["collage", "photo grid", "template", "arrange"],
    isFeatured: true,
    usageCount: 830_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 100,
    maxFiles: 20,
  },

  // ── Manual / Interactive Image Tools ─────────
  {
    id: "image-draw",
    slug: "draw",
    name: "Draw on Image",
    shortDescription: "Draw, annotate, and paint directly on your photos.",
    description: "Freehand draw on any image with a brush tool. Choose colors, brush size, and use an eraser. Perfect for annotations, highlights, and creative edits.",
    category: "image",
    icon: "Pen",
    tags: ["draw", "annotate", "paint", "brush", "doodle"],
    isNew: true,
    usageCount: 310_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-adjust",
    slug: "adjust",
    name: "Adjust Image",
    shortDescription: "Manually adjust brightness, contrast, and saturation.",
    description: "Fine-tune your photos with real-time sliders for brightness, contrast, and saturation. See a live preview as you adjust, then apply and download.",
    category: "image",
    icon: "SlidersHorizontal",
    tags: ["adjust", "brightness", "contrast", "saturation", "edit"],
    isNew: true,
    usageCount: 520_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-color-filter",
    slug: "color-filter",
    name: "Photo Filters",
    shortDescription: "Apply Instagram-style filters to your photos instantly.",
    description: "Apply stunning photo filters like Vivid, Warm, Cool, Vintage, Dramatic, and Fade. Preview in real-time and download the filtered image.",
    category: "image",
    icon: "Palette",
    tags: ["filter", "vintage", "vivid", "warm", "cool", "photo effects"],
    isNew: true,
    usageCount: 680_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "ai-paraphrase",
    slug: "paraphrase",
    name: "AI Paraphraser",
    description: "Paraphrase any text in seconds. Reword sentences while keeping the original meaning. Ideal for avoiding plagiarism, simplifying academic writing, or refreshing old content.",
    shortDescription: "Reword text while keeping the original meaning.",
    category: "ai-writing",
    icon: "Repeat2",
    tags: ["paraphrase", "reword", "plagiarism", "rephrase", "writing"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 920_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your text", description: "Copy and paste any text you want to paraphrase — an essay, email, article, or paragraph." },
      { title: "Select paraphrase mode", description: "Choose between Standard, Fluency, Creative, Formal, or Shorten modes to control how the text is reworded." },
      { title: "Copy the result", description: "Get your paraphrased text instantly. Copy it or compare it side by side with the original." },
    ],
  },
  {
    id: "ai-script-writer",
    slug: "script-writer",
    name: "Script Writer",
    description: "Write professional scripts for YouTube videos, TikToks, podcasts, ads, and presentations. Enter your topic and style, and get a complete, engaging script in seconds.",
    shortDescription: "Write scripts for YouTube, TikTok, podcasts & ads.",
    category: "ai-writing",
    icon: "Film",
    tags: ["script", "youtube", "tiktok", "podcast", "video", "content creator"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 480_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Choose platform & topic", description: "Select YouTube, TikTok, Podcast, Ad, or Presentation. Then enter your video/episode topic." },
      { title: "Set style & length", description: "Choose tone (Educational, Entertaining, Informative) and target duration (30s, 1 min, 5 min, 10 min+)." },
      { title: "Download your script", description: "Get a fully structured script with intro, main points, and CTA. Copy or download as a text file." },
    ],
  },

  {
    id: "instagram-bio-generator",
    slug: "instagram-bio",
    name: "Instagram Bio Generator",
    description: "Generate the perfect Instagram bio based on your mood and personality. Choose from Happy, Mysterious, Professional, Funny, Romantic, Motivational, Aesthetic, Savage, and more emotions.",
    shortDescription: "Generate Instagram bios based on your mood.",
    category: "ai-writing",
    icon: "AtSign",
    tags: ["instagram", "bio", "profile", "mood", "social media", "personality"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 780_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Select your mood", description: "Pick the emotion or vibe that matches your personality — Happy, Mysterious, Professional, Funny, Romantic, Motivational, and more." },
      { title: "Add personal details", description: "Optionally add your name, profession, interests, or a tagline to make the bio uniquely yours." },
      { title: "Copy your perfect bio", description: "Get 5 bio variations instantly. Pick the one you love and copy it directly to your Instagram profile." },
    ],
  },
  {
    id: "description-writer",
    slug: "description",
    name: "Description Writer",
    description: "Write compelling descriptions for anything — products, YouTube videos, blog posts, Amazon listings, apps, real estate, events, and more. Powered by AI.",
    shortDescription: "Write descriptions for any product or content.",
    category: "ai-writing",
    icon: "FileText",
    tags: ["description", "product", "youtube", "amazon", "listing", "copywriting", "ai"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 560_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Choose what you're describing", description: "Select the type — product, video, blog post, app, service, event, or anything else you need described." },
      { title: "Enter key details", description: "Add a title, key features, target audience, and tone. The more details you give, the better the output." },
      { title: "Copy or download your description", description: "Get a polished, ready-to-use description in seconds. Copy it directly or export as a text file." },
    ],
  },

  // ── More AI Writing Tools ─────────────────────
  {
    id: "ai-blog-writer",
    slug: "blog-writer",
    name: "AI Blog Writer",
    description: "Generate full blog posts with AI. Input a topic and keywords, get a structured, SEO-optimized article in seconds.",
    shortDescription: "Generate full blog posts with AI.",
    category: "ai-writing",
    icon: "Newspaper",
    tags: ["blog", "article", "content", "SEO", "AI"],
    isNew: true,
    isFeatured: true,
    usageCount: 520_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-email-writer",
    slug: "email-writer",
    name: "AI Email Writer",
    description: "Write professional emails in seconds. Choose from cold outreach, follow-up, apology, thank you, and 20+ templates.",
    shortDescription: "Write professional emails with AI.",
    category: "ai-writing",
    icon: "Mail",
    tags: ["email", "professional", "outreach", "AI"],
    isNew: true,
    usageCount: 380_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-social-caption",
    slug: "social-caption",
    name: "Social Media Caption",
    description: "Generate engaging captions for Instagram, Twitter, LinkedIn, and TikTok. Includes hashtag suggestions.",
    shortDescription: "Generate social media captions with AI.",
    category: "ai-writing",
    icon: "MessageCircle",
    tags: ["social media", "caption", "instagram", "linkedin"],
    isNew: true,
    usageCount: 640_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-headline-generator",
    slug: "headline",
    name: "Headline Generator",
    description: "Generate 10 compelling headline variations for any topic. Optimized for clicks, SEO, and social sharing.",
    shortDescription: "Generate compelling headlines with AI.",
    category: "ai-writing",
    icon: "Heading1",
    tags: ["headline", "title", "SEO", "clickbait"],
    usageCount: 290_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  // ── Converter ─────────────────────────────
  {
    id: "converter-json-formatter",
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data. Paste raw JSON to instantly beautify it with proper indentation, syntax highlighting, and error detection. Also supports JSON minification.",
    shortDescription: "Format, validate, and minify JSON instantly.",
    category: "converter",
    icon: "Braces",
    tags: ["json", "format", "validate", "minify", "developer", "api"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 680_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your JSON", description: "Copy and paste any JSON string, API response, or config file into the editor." },
      { title: "Format or minify", description: "Click Format to beautify with proper indentation, or Minify to compress for production use." },
      { title: "Copy the result", description: "Copy the formatted JSON to clipboard or download as a .json file." },
    ],
  },
  {
    id: "converter-base64",
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode plain text or files to Base64, or decode Base64 strings back to readable text. Useful for developers working with APIs, data URIs, and authentication tokens.",
    shortDescription: "Encode and decode Base64 strings instantly.",
    category: "converter",
    icon: "Hash",
    tags: ["base64", "encode", "decode", "developer", "api", "binary"],
    isNew: true,
    usageCount: 340_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter text or Base64", description: "Type or paste plain text to encode, or a Base64 string to decode." },
      { title: "Choose encode or decode", description: "Select whether you want to encode text to Base64 or decode Base64 back to plain text." },
      { title: "Copy the result", description: "Your encoded or decoded result appears instantly. Copy it with one click." },
    ],
  },

  // ── Video Downloader ──────────────────────────────
  {
    id: "video-downloader",
    slug: "downloader",
    name: "Video Downloader",
    description: "Download videos from YouTube, Instagram, Facebook, TikTok, Twitter/X, Pinterest, Vimeo, and 100+ other platforms. Paste the URL and choose your quality.",
    shortDescription: "Download videos from any social media platform.",
    category: "video",
    icon: "Download",
    tags: ["download", "youtube", "instagram", "tiktok", "facebook", "twitter", "social media"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_200_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste the video URL", description: "Copy the video URL from YouTube, Instagram, TikTok, Facebook, Twitter/X, or any other supported platform and paste it here." },
      { title: "Select quality & format", description: "Choose your preferred resolution (4K/1080p/720p/480p/360p) and format (MP4/WebM/MP3 for audio only)." },
      { title: "Download instantly", description: "Click Download and your video will be ready in seconds. No account needed, completely free." },
    ],
  },

  // ── Resume Tools ───────────────────────────────
  {
    id: "resume-builder",
    slug: "builder",
    name: "Resume Builder",
    description: "Create professional resumes with our easy-to-use builder. Fill in your details, choose a template, and download your resume in PDF or Word format.",
    shortDescription: "Build professional resumes with AI assistance.",
    category: "resume",
    icon: "FileEdit",
    tags: ["resume", "builder", "create", "pdf", "cv"],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    usageCount: 890_000,
    estimatedTime: "~5 min",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-analyzer",
    slug: "analyzer",
    name: "Resume Analyzer",
    description: "Upload your resume and get detailed AI-powered feedback. Fix common mistakes, improve formatting, and increase your chances of getting hired.",
    shortDescription: "Analyze resume and get improvement suggestions.",
    category: "resume",
    icon: "Search",
    tags: ["analyze", "review", "feedback", "ats score", "improve"],
    isPopular: true,
    isNew: true,
    usageCount: 420_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-skills-suggest",
    slug: "skills-suggest",
    name: "Skills Suggester",
    description: "Enter your job title or field and get personalized skill recommendations. Discover which skills employers are looking for in 2025.",
    shortDescription: "Get skill suggestions based on job title and industry.",
    category: "resume",
    icon: "Lightbulb",
    tags: ["skills", "suggestions", "keywords", "job search", "career"],
    isNew: true,
    usageCount: 310_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-cover-letter",
    slug: "cover-letter",
    name: "Cover Letter Generator",
    description: "Generate personalized cover letters in seconds. Input your details and the job description, get a tailored cover letter that matches your resume.",
    shortDescription: "Generate tailored cover letters for any job.",
    category: "resume",
    icon: "Mail",
    tags: ["cover letter", "application", "job", "generator", "ai"],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    usageCount: 580_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-formatter",
    slug: "formatter",
    name: "Resume Formatter",
    description: "Clean up and format your existing resume. Fix spacing, alignment, fonts, and structure to make it look professional and ATS-compliant.",
    shortDescription: "Format and clean up existing resumes.",
    category: "resume",
    icon: "AlignLeft",
    tags: ["format", "clean", "structure", "ats", "professional"],
    isNew: true,
    usageCount: 240_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-ats-checker",
    slug: "ats-checker",
    name: "ATS Score Checker",
    description: "Check how well your resume passes Applicant Tracking Systems. Upload your resume and paste a job description to get an ATS compatibility score with actionable fixes.",
    shortDescription: "Check your resume's ATS compatibility score.",
    category: "resume",
    icon: "ScanLine",
    tags: ["ats", "applicant tracking", "score", "job application", "keywords"],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    usageCount: 480_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-job-match",
    slug: "job-match",
    name: "Job Match Analyzer",
    description: "Compare your resume against a job description and get a match percentage. See exactly which skills and keywords you're missing to land the interview.",
    shortDescription: "Match your resume against any job description.",
    category: "resume",
    icon: "GitCompare",
    tags: ["job match", "job description", "keywords", "skills gap", "hiring"],
    isNew: true,
    usageCount: 350_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-summary",
    slug: "summary",
    name: "Professional Summary Generator",
    description: "Generate a compelling professional summary for your resume in seconds. Enter your job title, years of experience, and key skills — get a polished 3-sentence summary instantly.",
    shortDescription: "Generate a compelling resume summary with AI.",
    category: "resume",
    icon: "Sparkles",
    tags: ["summary", "objective", "profile", "ai", "resume header"],
    isNew: true,
    isFeatured: true,
    usageCount: 390_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-linkedin",
    slug: "linkedin",
    name: "LinkedIn Profile Writer",
    description: "Optimize your LinkedIn profile with AI. Generate a compelling headline, About section, and experience bullets that attract recruiters and rank higher in searches.",
    shortDescription: "Write an optimized LinkedIn profile with AI.",
    category: "resume",
    icon: "Linkedin",
    tags: ["linkedin", "profile", "headline", "about", "networking"],
    isNew: true,
    isFeatured: true,
    usageCount: 270_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-interview-prep",
    slug: "interview-prep",
    name: "Interview Question Generator",
    description: "Upload your resume or enter your job title and get 20+ personalized interview questions with model answers. Prepare for behavioral, technical, and situational questions.",
    shortDescription: "Generate interview questions from your resume.",
    category: "resume",
    icon: "MessageSquare",
    tags: ["interview", "questions", "preparation", "behavioral", "hr"],
    isNew: true,
    usageCount: 310_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-keywords",
    slug: "keywords",
    name: "Resume Keyword Optimizer",
    description: "Find and add the right keywords to your resume. Paste your resume and a job description to discover missing keywords, keyword density, and placement suggestions.",
    shortDescription: "Optimize resume keywords to beat ATS filters.",
    category: "resume",
    icon: "Tags",
    tags: ["keywords", "optimization", "ats", "search", "density"],
    isNew: true,
    usageCount: 220_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
];

// ─────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────

export function getToolBySlug(slug: string, category: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug && t.category === category);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getFeaturedTools(limit = 8): Tool[] {
  return TOOLS.filter((t) => t.isFeatured).slice(0, limit);
}

export function getPopularTools(limit = 12): Tool[] {
  return TOOLS.filter((t) => t.isPopular)
    .sort((a, b) => (b.usageCount ?? 0) - (a.usageCount ?? 0))
    .slice(0, limit);
}

export { TOOL_CATEGORIES } from "@/config/navigation";
