import type { Tool, ToolCategory } from "@/types";

// ─────────────────────────────────────────────
// Tool registry
// In production this comes from a database/CMS.
// This file is the static type-safe fallback and
// source of truth for generateStaticParams.
// ─────────────────────────────────────────────

export const TOOLS: Tool[] = [
  // ── PDF Tools ──────────────────────────────
  {
    id: "pdf-compress",
    slug: "compress",
    name: "Compress PDF",
    description:
      "Reduce PDF file size while maintaining quality. Supports batch compression of multiple files at once with smart optimization.",
    shortDescription: "Reduce PDF file size without losing quality.",
    category: "pdf",
    icon: "FileDown",
    tags: ["compress", "optimize", "reduce size"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_400_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 20,
  },
  {
    id: "pdf-merge",
    slug: "merge",
    name: "Merge PDF",
    description:
      "Combine multiple PDF files into one. Drag to reorder pages before merging for precise document control.",
    shortDescription: "Combine multiple PDFs into one document.",
    category: "pdf",
    icon: "Combine",
    tags: ["merge", "combine", "join"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_800_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 50,
  },
  {
    id: "pdf-split",
    slug: "split",
    name: "Split PDF",
    description: "Split a PDF into individual pages or custom page ranges. Extract exactly what you need.",
    shortDescription: "Split PDF into individual pages or ranges.",
    category: "pdf",
    icon: "Scissors",
    tags: ["split", "separate", "extract pages"],
    usageCount: 980_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-to-word",
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF documents to editable Word (.docx) files with AI-powered layout preservation.",
    shortDescription: "Convert PDF to editable Word document.",
    category: "pdf",
    icon: "FileEdit",
    tags: ["convert", "word", "docx", "editable"],
    isNew: true,
    isFeatured: true,
    usageCount: 650_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },
  {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert each PDF page into high-quality JPG images. Choose resolution and quality settings.",
    shortDescription: "Convert PDF pages to JPG images.",
    category: "pdf",
    icon: "Image",
    tags: ["convert", "jpg", "image", "export"],
    usageCount: 870_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 10,
  },
  {
    id: "pdf-rotate",
    slug: "rotate",
    name: "Rotate PDF",
    description: "Rotate individual pages or the entire PDF document. Fix incorrectly scanned documents in seconds.",
    shortDescription: "Rotate PDF pages to correct orientation.",
    category: "pdf",
    icon: "RotateCw",
    tags: ["rotate", "orientation", "fix"],
    usageCount: 420_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },

  // ── Image Tools ─────────────────────────────
  {
    id: "image-compress",
    slug: "compress",
    name: "Compress Image",
    description: "Compress JPEG, PNG, WebP images up to 90% smaller with no visible quality loss using smart AI compression.",
    shortDescription: "Compress images without visible quality loss.",
    category: "image",
    icon: "ImageDown",
    tags: ["compress", "optimize", "reduce size"],
    isPopular: true,
    isFeatured: true,
    usageCount: 3_200_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
    maxFileSizeMB: 25,
    maxFiles: 30,
  },
  {
    id: "image-resize",
    slug: "resize",
    name: "Resize Image",
    description: "Resize images to exact pixel dimensions or percentage. Maintain aspect ratio with smart crop options.",
    shortDescription: "Resize images to any dimension.",
    category: "image",
    icon: "Scaling",
    tags: ["resize", "dimensions", "scale"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_500_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-bg-remove",
    slug: "remove-background",
    name: "Remove Background",
    description: "AI-powered background removal. Get transparent PNG in seconds. Perfect for product photos and portraits.",
    shortDescription: "Remove image background with AI instantly.",
    category: "image",
    icon: "Eraser",
    tags: ["background removal", "transparent", "AI"],
    isNew: true,
    isFeatured: true,
    usageCount: 2_100_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 10,
    maxFiles: 5,
  },
  {
    id: "image-convert",
    slug: "convert",
    name: "Convert Image",
    description: "Convert between JPG, PNG, WebP, AVIF, GIF and more. Batch convert hundreds of images at once.",
    shortDescription: "Convert between all image formats.",
    category: "image",
    icon: "ArrowRightLeft",
    tags: ["convert", "format", "jpg", "png", "webp"],
    usageCount: 780_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp", ".tiff"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  // ── Video ────────────────────────────────────
  {
    id: "video-downloader",
    slug: "downloader",
    name: "Video Downloader",
    description: "Download videos from YouTube, Instagram, TikTok, Facebook, Twitter/X, Pinterest, Vimeo, Dailymotion, Twitch, Reddit and 100+ other platforms. Paste the URL and choose your quality.",
    shortDescription: "Download videos from any platform by URL.",
    category: "video",
    icon: "Download",
    tags: ["download", "youtube", "instagram", "tiktok", "facebook", "twitter", "social media", "video"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_200_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste the video URL", description: "Copy the video URL from YouTube, Instagram, TikTok, Facebook, Twitter/X or any supported platform and paste it." },
      { title: "Select quality & format", description: "Choose your preferred resolution (4K/1080p/720p/480p/360p) and format (MP4 or MP3 audio)." },
      { title: "Download instantly", description: "Click Download and your video will be saved. No account needed, completely free." },
    ],
  },

  // ── AI Writing ──────────────────────────────
  {
    id: "ai-summarize",
    slug: "summarize",
    name: "AI Summarizer",
    description: "Summarize long articles, documents, or text into clear bullet points or concise paragraphs with one click.",
    shortDescription: "Summarize any text with AI in seconds.",
    category: "ai-writing",
    icon: "AlignLeft",
    tags: ["summarize", "condense", "abstract"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_600_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-translate",
    slug: "translate",
    name: "AI Translator",
    description: "Translate text between 100+ languages with context-aware AI translation that preserves tone and meaning.",
    shortDescription: "Translate text into 100+ languages.",
    category: "ai-writing",
    icon: "Languages",
    tags: ["translate", "language", "localize"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_300_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-rewrite",
    slug: "rewrite",
    name: "AI Rewriter",
    description: "Rewrite any text to improve clarity, tone, or style. Choose from professional, casual, formal, or creative modes.",
    shortDescription: "Rewrite text to improve clarity and tone.",
    category: "ai-writing",
    icon: "RefreshCw",
    tags: ["rewrite", "paraphrase", "rephrase"],
    isNew: true,
    usageCount: 740_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-grammar",
    slug: "grammar-check",
    name: "Grammar Checker",
    description: "Fix grammar, spelling, and punctuation errors instantly. Get detailed explanations for every correction made.",
    shortDescription: "Check and fix grammar errors with AI.",
    category: "ai-writing",
    icon: "SpellCheck",
    tags: ["grammar", "spell check", "proofread"],
    usageCount: 1_100_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── More PDF Tools ──────────────────────────
  {
    id: "pdf-watermark",
    slug: "watermark",
    name: "Add Watermark",
    description: "Add text or image watermarks to PDF documents. Customize position, opacity, font, and color.",
    shortDescription: "Add watermark text or logo to PDF.",
    category: "pdf",
    icon: "Stamp",
    tags: ["watermark", "stamp", "brand", "protect"],
    usageCount: 310_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 10,
  },
  {
    id: "pdf-to-excel",
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Convert PDF tables and data into editable Excel spreadsheets (.xlsx) with AI-powered table detection.",
    shortDescription: "Convert PDF tables to Excel spreadsheet.",
    category: "pdf",
    icon: "TableProperties",
    tags: ["convert", "excel", "xlsx", "table"],
    isNew: true,
    usageCount: 520_000,
    estimatedTime: "~12s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },
  {
    id: "pdf-sign",
    slug: "sign",
    name: "Sign PDF",
    description: "Add digital signatures to PDF files. Draw, type, or upload your signature and place it anywhere.",
    shortDescription: "Add digital signature to PDF.",
    category: "pdf",
    icon: "PenLine",
    tags: ["sign", "signature", "esign", "digital"],
    isFeatured: true,
    isNew: true,
    usageCount: 680_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 1,
  },
  {
    id: "pdf-page-numbers",
    slug: "page-numbers",
    name: "Add Page Numbers",
    description: "Add customizable page numbers to PDF documents. Choose position, font, size, start number, and format.",
    shortDescription: "Add page numbers to PDF documents.",
    category: "pdf",
    icon: "Hash",
    tags: ["page numbers", "numbering", "footer", "header"],
    usageCount: 190_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-ocr",
    slug: "ocr",
    name: "PDF OCR",
    description: "Extract text from scanned PDFs and images using AI-powered OCR. Converts scanned documents into searchable, editable text. Supports 40+ languages.",
    shortDescription: "Extract text from scanned PDFs with OCR.",
    category: "pdf",
    icon: "ScanText",
    tags: ["ocr", "scan", "extract text", "scanned", "searchable"],
    isNew: true,
    isFeatured: true,
    usageCount: 390_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".pdf", ".jpg", ".jpeg", ".png", ".tiff"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },

  {
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG, PNG, or WebP images to a single PDF. Drag to reorder, choose page size and margins.",
    shortDescription: "Convert images to a PDF document.",
    category: "pdf",
    icon: "FileImage",
    tags: ["jpg", "image", "convert", "create pdf"],
    isPopular: true,
    usageCount: 1_100_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 50,
  },

  // ── More Image Tools ─────────────────────────
  {
    id: "image-watermark",
    slug: "watermark",
    name: "Image Watermark",
    description: "Add text or logo watermarks to images. Customize opacity, position, size, and font. Batch process multiple images.",
    shortDescription: "Add text or logo watermark to images.",
    category: "image",
    icon: "Stamp",
    tags: ["watermark", "logo", "brand", "protect"],
    usageCount: 390_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-to-pdf",
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert one or multiple images to a single PDF file. Supports JPG, PNG, WebP. Customize page size and margins.",
    shortDescription: "Convert images to PDF in one click.",
    category: "image",
    icon: "FilePlus",
    tags: ["convert", "pdf", "jpg", "png"],
    usageCount: 720_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 50,
    maxFiles: 30,
  },
  {
    id: "qr-code-generator",
    slug: "qr-code",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, Wi-Fi, vCard, and more. Customize colors, size, and download as PNG or SVG.",
    shortDescription: "Generate custom QR codes instantly.",
    category: "image",
    icon: "QrCode",
    tags: ["qr code", "generator", "url", "barcode"],
    isNew: true,
    isFeatured: true,
    usageCount: 1_400_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "image-upscale",
    slug: "upscale",
    name: "AI Image Upscaler",
    description: "Upscale images 2x or 4x using AI super-resolution. Enhances details and sharpness without pixelation.",
    shortDescription: "Upscale images 2x–4x with AI.",
    category: "image",
    icon: "Maximize2",
    tags: ["upscale", "enhance", "AI", "resolution", "super resolution"],
    isFeatured: true,
    isNew: true,
    usageCount: 960_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 10,
    maxFiles: 5,
  },
  {
    id: "meme-generator",
    slug: "meme",
    name: "Meme Generator",
    description: "Create memes with popular templates or upload your own image. Add top and bottom text with custom fonts and colors.",
    shortDescription: "Create memes with templates or custom images.",
    category: "image",
    icon: "Smile",
    tags: ["meme", "fun", "text", "social media"],
    isNew: true,
    usageCount: 450_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },

  // ── Image Effects (new) ────────────────────
  {
    id: "image-black-white",
    slug: "black-white",
    name: "Photo Black & White",
    shortDescription: "Convert any photo to black & white instantly.",
    description: "Convert photos to stunning black and white with adjustable contrast and brightness controls.",
    category: "image",
    icon: "Circle",
    tags: ["black white", "grayscale", "monochrome", "filter"],
    usageCount: 890_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-rotate",
    slug: "rotate",
    name: "Rotate Image",
    shortDescription: "Rotate images 90°, 180°, or any custom angle.",
    description: "Rotate images clockwise or counter-clockwise by 90°, 180°, 270°, or any custom angle.",
    category: "image",
    icon: "RotateCw",
    tags: ["rotate", "turn", "angle", "orientation"],
    usageCount: 520_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-flip",
    slug: "flip",
    name: "Image Flipper",
    shortDescription: "Flip or mirror images horizontally or vertically.",
    description: "Instantly flip or mirror images horizontally (left-right) or vertically (top-bottom).",
    category: "image",
    icon: "FlipHorizontal",
    tags: ["flip", "mirror", "horizontal", "vertical"],
    usageCount: 440_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "ai-paraphrase",
    slug: "paraphrase",
    name: "AI Paraphraser",
    description: "Paraphrase any text in seconds. Reword sentences while keeping the original meaning. Ideal for avoiding plagiarism, simplifying academic writing, or refreshing old content.",
    shortDescription: "Reword text while keeping the original meaning.",
    category: "ai-writing",
    icon: "Repeat2",
    tags: ["paraphrase", "reword", "plagiarism", "rephrase", "writing"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 920_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your text", description: "Copy and paste any text you want to paraphrase — an essay, email, article, or paragraph." },
      { title: "Select paraphrase mode", description: "Choose between Standard, Fluency, Creative, Formal, or Shorten modes to control how the text is reworded." },
      { title: "Copy the result", description: "Get your paraphrased text instantly. Copy it or compare it side by side with the original." },
    ],
  },
  {
    id: "ai-script-writer",
    slug: "script-writer",
    name: "Script Writer",
    description: "Write professional scripts for YouTube videos, TikToks, podcasts, ads, and presentations. Enter your topic and style, and get a complete, engaging script in seconds.",
    shortDescription: "Write scripts for YouTube, TikTok, podcasts & ads.",
    category: "ai-writing",
    icon: "Film",
    tags: ["script", "youtube", "tiktok", "podcast", "video", "content creator"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 480_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Choose platform & topic", description: "Select YouTube, TikTok, Podcast, Ad, or Presentation. Then enter your video/episode topic." },
      { title: "Set style & length", description: "Choose tone (Educational, Entertaining, Informative) and target duration (30s, 1 min, 5 min, 10 min+)." },
      { title: "Download your script", description: "Get a fully structured script with intro, main points, and CTA. Copy or download as a text file." },
    ],
  },

  {
    id: "instagram-bio-generator",
    slug: "instagram-bio",
    name: "Instagram Bio Generator",
    description: "Generate the perfect Instagram bio based on your mood and personality. Choose from Happy, Mysterious, Professional, Funny, Romantic, Motivational, Aesthetic, Savage, and more emotions.",
    shortDescription: "Generate Instagram bios based on your mood.",
    category: "ai-writing",
    icon: "AtSign",
    tags: ["instagram", "bio", "profile", "mood", "social media", "personality"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 780_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Select your mood", description: "Pick the emotion or vibe that matches your personality — Happy, Mysterious, Professional, Funny, Romantic, Motivational, and more." },
      { title: "Add personal details", description: "Optionally add your name, profession, interests, or a tagline to make the bio uniquely yours." },
      { title: "Copy your perfect bio", description: "Get 5 bio variations instantly. Pick the one you love and copy it directly to your Instagram profile." },
    ],
  },
  {
    id: "description-writer",
    slug: "description",
    name: "Description Writer",
    description: "Write compelling descriptions for anything — products, YouTube videos, blog posts, Amazon listings, apps, real estate, events, and more. Powered by AI.",
    shortDescription: "Write descriptions for any product or content.",
    category: "ai-writing",
    icon: "FileText",
    tags: ["description", "product", "youtube", "amazon", "listing", "copywriting", "ai"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 560_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Choose what you're describing", description: "Select the type — product, video, blog post, app, service, event, or anything else you need described." },
      { title: "Enter key details", description: "Add a title, key features, target audience, and tone. The more details you give, the better the output." },
      { title: "Copy or download your description", description: "Get a polished, ready-to-use description in seconds. Copy it directly or export as a text file." },
    ],
  },

  // ── More AI Writing Tools ─────────────────────
  {
    id: "ai-blog-writer",
    slug: "blog-writer",
    name: "AI Blog Writer",
    description: "Generate full blog posts with AI. Input a topic and keywords, get a structured, SEO-optimized article in seconds.",
    shortDescription: "Generate full blog posts with AI.",
    category: "ai-writing",
    icon: "Newspaper",
    tags: ["blog", "article", "content", "SEO", "AI"],
    isNew: true,
    isFeatured: true,
    usageCount: 520_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-email-writer",
    slug: "email-writer",
    name: "AI Email Writer",
    description: "Write professional emails in seconds. Choose from cold outreach, follow-up, apology, thank you, and 20+ templates.",
    shortDescription: "Write professional emails with AI.",
    category: "ai-writing",
    icon: "Mail",
    tags: ["email", "professional", "outreach", "AI"],
    isNew: true,
    usageCount: 380_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-social-caption",
    slug: "social-caption",
    name: "Social Media Caption",
    description: "Generate engaging captions for Instagram, Twitter, LinkedIn, and TikTok. Includes hashtag suggestions.",
    shortDescription: "Generate social media captions with AI.",
    category: "ai-writing",
    icon: "MessageCircle",
    tags: ["social media", "caption", "instagram", "linkedin"],
    isNew: true,
    usageCount: 640_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-headline-generator",
    slug: "headline",
    name: "Headline Generator",
    description: "Generate 10 compelling headline variations for any topic. Optimized for clicks, SEO, and social sharing.",
    shortDescription: "Generate compelling headlines with AI.",
    category: "ai-writing",
    icon: "Heading1",
    tags: ["headline", "title", "SEO", "clickbait"],
    usageCount: 290_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  // ── Converter ─────────────────────────────
  {
    id: "converter-json-formatter",
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data. Paste raw JSON to instantly beautify it with proper indentation, syntax highlighting, and error detection. Also supports JSON minification.",
    shortDescription: "Format, validate, and minify JSON instantly.",
    category: "converter",
    icon: "Braces",
    tags: ["json", "format", "validate", "minify", "developer", "api"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 680_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your JSON", description: "Copy and paste any JSON string, API response, or config file into the editor." },
      { title: "Format or minify", description: "Click Format to beautify with proper indentation, or Minify to compress for production use." },
      { title: "Copy the result", description: "Copy the formatted JSON to clipboard or download as a .json file." },
    ],
  },
  {
    id: "converter-base64",
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode plain text or files to Base64, or decode Base64 strings back to readable text. Useful for developers working with APIs, data URIs, and authentication tokens.",
    shortDescription: "Encode and decode Base64 strings instantly.",
    category: "converter",
    icon: "Hash",
    tags: ["base64", "encode", "decode", "developer", "api", "binary"],
    isNew: true,
    usageCount: 340_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter text or Base64", description: "Type or paste plain text to encode, or a Base64 string to decode." },
      { title: "Choose encode or decode", description: "Select whether you want to encode text to Base64 or decode Base64 back to plain text." },
      { title: "Copy the result", description: "Your encoded or decoded result appears instantly. Copy it with one click." },
    ],
  },


  // ── Resume Tools ───────────────────────────────
  {
    id: "resume-builder",
    slug: "builder",
    name: "Resume Builder",
    description: "Create professional resumes with our easy-to-use builder. Fill in your details, choose a template, and download your resume in PDF or Word format.",
    shortDescription: "Build professional resumes with AI assistance.",
    category: "resume",
    icon: "FileEdit",
    tags: ["resume", "builder", "create", "pdf", "cv"],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    usageCount: 890_000,
    estimatedTime: "~5 min",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-analyzer",
    slug: "analyzer",
    name: "Resume Analyzer",
    description: "Upload your resume and get detailed AI-powered feedback. Fix common mistakes, improve formatting, and increase your chances of getting hired.",
    shortDescription: "Analyze resume and get improvement suggestions.",
    category: "resume",
    icon: "Search",
    tags: ["analyze", "review", "feedback", "ats score", "improve"],
    isPopular: true,
    isNew: true,
    usageCount: 420_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-skills-suggest",
    slug: "skills-suggest",
    name: "Skills Suggester",
    description: "Enter your job title or field and get personalized skill recommendations. Discover which skills employers are looking for in 2025.",
    shortDescription: "Get skill suggestions based on job title and industry.",
    category: "resume",
    icon: "Lightbulb",
    tags: ["skills", "suggestions", "keywords", "job search", "career"],
    isNew: true,
    usageCount: 310_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-cover-letter",
    slug: "cover-letter",
    name: "Cover Letter Generator",
    description: "Generate personalized cover letters in seconds. Input your details and the job description, get a tailored cover letter that matches your resume.",
    shortDescription: "Generate tailored cover letters for any job.",
    category: "resume",
    icon: "Mail",
    tags: ["cover letter", "application", "job", "generator", "ai"],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    usageCount: 580_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-formatter",
    slug: "formatter",
    name: "Resume Formatter",
    description: "Clean up and format your existing resume. Fix spacing, alignment, fonts, and structure to make it look professional and ATS-compliant.",
    shortDescription: "Format and clean up existing resumes.",
    category: "resume",
    icon: "AlignLeft",
    tags: ["format", "clean", "structure", "ats", "professional"],
    isNew: true,
    usageCount: 240_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-ats-checker",
    slug: "ats-checker",
    name: "ATS Score Checker",
    description: "Check how well your resume passes Applicant Tracking Systems. Upload your resume and paste a job description to get an ATS compatibility score with actionable fixes.",
    shortDescription: "Check your resume's ATS compatibility score.",
    category: "resume",
    icon: "ScanLine",
    tags: ["ats", "applicant tracking", "score", "job application", "keywords"],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    usageCount: 480_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-job-match",
    slug: "job-match",
    name: "Job Match Analyzer",
    description: "Compare your resume against a job description and get a match percentage. See exactly which skills and keywords you're missing to land the interview.",
    shortDescription: "Match your resume against any job description.",
    category: "resume",
    icon: "GitCompare",
    tags: ["job match", "job description", "keywords", "skills gap", "hiring"],
    isNew: true,
    usageCount: 350_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-summary",
    slug: "resume-summary",
    name: "Professional Summary Generator",
    description: "Generate a compelling professional summary for your resume in seconds. Enter your job title, years of experience, and key skills — get a polished 3-sentence summary instantly.",
    shortDescription: "Generate a compelling resume summary with AI.",
    category: "resume",
    icon: "Sparkles",
    tags: ["summary", "objective", "profile", "ai", "resume header"],
    isNew: true,
    isFeatured: true,
    usageCount: 390_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-linkedin",
    slug: "linkedin-writer",
    name: "LinkedIn Profile Writer",
    description: "Optimize your LinkedIn profile with AI. Generate a compelling headline, About section, and experience bullets that attract recruiters and rank higher in searches.",
    shortDescription: "Write an optimized LinkedIn profile with AI.",
    category: "resume",
    icon: "Linkedin",
    tags: ["linkedin", "profile", "headline", "about", "networking"],
    isNew: true,
    isFeatured: true,
    usageCount: 270_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-interview-prep",
    slug: "interview-prep",
    name: "Interview Question Generator",
    description: "Upload your resume or enter your job title and get 20+ personalized interview questions with model answers. Prepare for behavioral, technical, and situational questions.",
    shortDescription: "Generate interview questions from your resume.",
    category: "resume",
    icon: "MessageSquare",
    tags: ["interview", "questions", "preparation", "behavioral", "hr"],
    isNew: true,
    usageCount: 310_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-keywords",
    slug: "keyword-optimizer",
    name: "Resume Keyword Optimizer",
    description: "Find and add the right keywords to your resume. Paste your resume and a job description to discover missing keywords, keyword density, and placement suggestions.",
    shortDescription: "Optimize resume keywords to beat ATS filters.",
    category: "resume",
    icon: "Tags",
    tags: ["keywords", "optimization", "ats", "search", "density"],
    isNew: true,
    usageCount: 220_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── Resignation Letter ─────────────────────────
  {
    id: "resume-resignation",
    slug: "resignation-letter",
    name: "Resignation Letter Writer",
    description: "Write a professional resignation letter in seconds. Choose your tone, notice period, and reasons — get a polished letter ready to send to your employer.",
    shortDescription: "Write a professional resignation letter with AI.",
    category: "resume",
    icon: "FileX2",
    tags: ["resignation", "quit job", "letter", "notice period", "professional"],
    isNew: true,
    usageCount: 290_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter your details", description: "Add your name, company, manager, position, and last working day." },
      { title: "Choose your tone", description: "Select from Professional, Grateful, Formal, or Brief tone styles." },
      { title: "Copy your letter", description: "Get a complete, ready-to-send resignation letter." },
    ],
  },

  // ── More Converter Tools ──────────────────────
  {
    id: "converter-url",
    slug: "url-encode",
    name: "URL Encoder / Decoder",
    description: "Encode and decode URLs and query strings. Convert special characters to percent-encoded format or back to readable text. Essential for web developers.",
    shortDescription: "Encode and decode URLs instantly.",
    category: "converter",
    icon: "Link2",
    tags: ["url", "encode", "decode", "percent encoding", "uri", "developer"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 520_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your URL or text", description: "Enter any URL, query string, or text that needs to be encoded or decoded." },
      { title: "Choose encode or decode", description: "Encode converts special characters to %XX format. Decode converts %XX back to readable characters." },
      { title: "Copy the result", description: "Your encoded or decoded URL is ready instantly. Copy it to clipboard with one click." },
    ],
  },
  {
    id: "converter-word-count",
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, paragraphs, and reading time. Analyze text density instantly. Paste any text to see detailed stats.",
    shortDescription: "Count words, characters, and reading time.",
    category: "converter",
    icon: "Type",
    tags: ["word count", "character count", "reading time", "text analysis", "writer"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 890_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your text", description: "Copy and paste any text — an essay, article, email, or document." },
      { title: "See instant stats", description: "Get word count, character count (with/without spaces), sentence count, paragraph count, and estimated reading time." },
      { title: "Check keyword density", description: "See the top keywords and their frequency to check for repetition." },
    ],
  },
  {
    id: "converter-password",
    slug: "password-gen",
    name: "Password Generator",
    description: "Generate strong, secure random passwords. Customize length, include uppercase, lowercase, numbers, and special characters. Check password strength instantly.",
    shortDescription: "Generate strong random passwords instantly.",
    category: "converter",
    icon: "KeyRound",
    tags: ["password", "generator", "security", "random", "strong password"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_100_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Set your requirements", description: "Choose password length and which character types to include: uppercase, lowercase, numbers, and symbols." },
      { title: "Generate instantly", description: "Click Generate to create a cryptographically secure random password." },
      { title: "Copy & use", description: "Copy your new password to clipboard with one click. Generate as many as you need." },
    ],
  },
  {
    id: "converter-color",
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, and HSL formats instantly. Pick colors visually, see live previews, and copy values for CSS or design tools.",
    shortDescription: "Convert colors between HEX, RGB, HSL formats.",
    category: "converter",
    icon: "Pipette",
    tags: ["color", "hex", "rgb", "hsl", "design", "css"],
    isNew: true,
    isFeatured: true,
    usageCount: 430_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter a color value", description: "Type a HEX code (#ff5733), RGB (255, 87, 51), or HSL value. Or use the color picker." },
      { title: "See all formats", description: "Get the color in HEX, RGB, and HSL formats simultaneously with a live preview." },
      { title: "Copy any format", description: "Copy the color value in whichever format you need for CSS or design tools." },
    ],
  },
  {
    id: "converter-csv-json",
    slug: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV files or pasted CSV data to JSON format. Supports custom delimiters and headers. Perfect for data transformation and API work.",
    shortDescription: "Convert CSV data to JSON format.",
    category: "converter",
    icon: "Table2",
    tags: ["csv", "json", "convert", "data", "api", "developer"],
    isNew: true,
    usageCount: 360_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your CSV data", description: "Copy and paste CSV data with or without headers. Supports comma, semicolon, or tab delimiters." },
      { title: "Convert to JSON", description: "Click Convert to transform your CSV into a clean JSON array." },
      { title: "Copy or download", description: "Copy the JSON to clipboard or download it as a .json file." },
    ],
  },
  {
    id: "converter-html-markdown",
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML code to clean Markdown format. Paste HTML from any website or document and get clean .md output. Also supports Markdown to HTML.",
    shortDescription: "Convert HTML to Markdown and vice versa.",
    category: "converter",
    icon: "FileCode2",
    tags: ["html", "markdown", "convert", "documentation", "developer"],
    isNew: true,
    usageCount: 280_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-markdown",
    slug: "markdown",
    name: "Markdown Editor",
    description: "Write Markdown with a live HTML preview side by side. Supports GitHub Flavored Markdown. Copy the rendered HTML or export the .md file.",
    shortDescription: "Write Markdown with live HTML preview.",
    category: "converter",
    icon: "Notebook",
    tags: ["markdown", "preview", "editor", "documentation", "readme"],
    isNew: true,
    usageCount: 320_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── Ad Copy ──────────────────────────────────
  {
    id: "ai-ad-copy",
    slug: "ad-copy",
    name: "AI Ad Copy Writer",
    description: "Generate high-converting ad copy for Google Ads, Facebook Ads, Instagram, and more. Enter your product and get headlines, descriptions, and CTAs optimized for conversions.",
    shortDescription: "Generate high-converting ad copy with AI.",
    category: "ai-writing",
    icon: "Megaphone",
    tags: ["ad copy", "advertising", "google ads", "facebook ads", "marketing", "copywriting"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 410_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Describe your product", description: "Enter your product name, key benefits, target audience, and the platform you're advertising on." },
      { title: "Choose format & tone", description: "Select headline count, description length, and tone (persuasive, urgent, friendly, professional)." },
      { title: "Copy your ad copy", description: "Get multiple variations of headlines and descriptions for A/B testing in your campaigns." },
    ],
  },

  // ── Calculator Tools ─────────────────────────
  {
    id: "calc-age",
    slug: "age",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, and days from any date of birth. Also shows next birthday countdown and total days lived.",
    shortDescription: "Calculate exact age from date of birth.",
    category: "calculator",
    icon: "Cake",
    tags: ["age", "birthday", "date of birth", "years", "months"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_800_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-bmi",
    slug: "bmi",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index (BMI) with height and weight. Supports metric (kg/cm) and imperial (lbs/ft) units. Shows BMI category and healthy weight range.",
    shortDescription: "Calculate BMI with height and weight.",
    category: "calculator",
    icon: "Activity",
    tags: ["bmi", "body mass index", "health", "weight", "fitness"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_900_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-percentage",
    slug: "percentage",
    name: "Percentage Calculator",
    description: "Calculate percentages instantly. Find what % one number is of another, calculate % increase/decrease, or find the original value from a percentage.",
    shortDescription: "Calculate any percentage instantly.",
    category: "calculator",
    icon: "Percent",
    tags: ["percentage", "percent", "discount", "increase", "decrease", "math"],
    isPopular: true,
    isFeatured: true,
    usageCount: 3_400_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-emi",
    slug: "emi",
    name: "EMI Calculator",
    description: "Calculate monthly loan EMI for home loans, car loans, and personal loans. Shows full amortization schedule with principal and interest breakdown.",
    shortDescription: "Calculate monthly loan EMI instantly.",
    category: "calculator",
    icon: "Landmark",
    tags: ["emi", "loan", "interest", "home loan", "car loan", "mortgage"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_100_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-tip",
    slug: "tip",
    name: "Tip Calculator",
    description: "Calculate restaurant tip and split bills among friends. Enter bill amount, tip percentage, and number of people to get per-person amounts instantly.",
    shortDescription: "Calculate tip and split bills easily.",
    category: "calculator",
    icon: "Receipt",
    tags: ["tip", "restaurant", "bill split", "split", "gratuity"],
    usageCount: 980_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-discount",
    slug: "discount",
    name: "Discount Calculator",
    description: "Calculate sale price after discount, find discount percentage, or work backwards from a discounted price. Perfect for shopping and pricing.",
    shortDescription: "Calculate discounts and sale prices.",
    category: "calculator",
    icon: "Tag",
    tags: ["discount", "sale", "price", "coupon", "savings", "shopping"],
    isPopular: true,
    usageCount: 1_600_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-date",
    slug: "date-diff",
    name: "Date Calculator",
    description: "Calculate the difference between two dates in days, weeks, months, and years. Add or subtract days from a date. Find what day of the week any date falls on.",
    shortDescription: "Calculate date differences and add/subtract days.",
    category: "calculator",
    icon: "CalendarDays",
    tags: ["date", "days between", "date difference", "calendar", "deadline"],
    usageCount: 1_200_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── More Converter Utility Tools ──────────────
  {
    id: "converter-case",
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case. Process any amount of text instantly.",
    shortDescription: "Convert text between all case formats.",
    category: "converter",
    icon: "CaseSensitive",
    tags: ["case", "uppercase", "lowercase", "camelCase", "title case", "snake_case", "developer"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_800_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your text", description: "Enter any text that needs to be converted to a different case format." },
      { title: "Choose your case", description: "Select from UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, or kebab-case." },
      { title: "Copy the result", description: "Your converted text appears instantly. Copy it with one click." },
    ],
  },
  {
    id: "converter-lorem",
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder Lorem Ipsum text for designs and mockups. Choose number of words, sentences, or paragraphs. Includes classic and modern variations.",
    shortDescription: "Generate placeholder text for designs.",
    category: "converter",
    icon: "AlignLeft",
    tags: ["lorem ipsum", "placeholder", "dummy text", "design", "mockup", "developer"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_400_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-number-base",
    slug: "number-converter",
    name: "Number Base Converter",
    description: "Convert numbers between decimal, binary, hexadecimal, and octal. Instantly see the same number in all four bases side by side.",
    shortDescription: "Convert numbers between decimal, binary, hex, and octal.",
    category: "converter",
    icon: "Hash",
    tags: ["binary", "hex", "decimal", "octal", "base", "developer", "convert"],
    isNew: true,
    usageCount: 580_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-uuid",
    slug: "uuid-gen",
    name: "UUID Generator",
    description: "Generate version 4 UUID (Universally Unique Identifier) instantly. Generate single or bulk UUIDs. Perfect for database IDs and development.",
    shortDescription: "Generate UUID/GUID instantly.",
    category: "converter",
    icon: "Fingerprint",
    tags: ["uuid", "guid", "unique id", "identifier", "developer", "database"],
    isNew: true,
    isFeatured: true,
    usageCount: 760_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-text-reverse",
    slug: "text-reverser",
    name: "Text Reverser",
    description: "Reverse any text instantly. Reverse entire string, reverse word order, or reverse each word individually. Also supports upside-down text.",
    shortDescription: "Reverse text, words, or sentences.",
    category: "converter",
    icon: "Undo2",
    tags: ["reverse", "text", "flip", "mirror", "backwards"],
    usageCount: 420_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-random-number",
    slug: "random-number",
    name: "Random Number Generator",
    description: "Generate random numbers in any range. Generate single numbers, lists, dice rolls, lottery numbers, or coin flips. Set custom min/max values.",
    shortDescription: "Generate random numbers in any range.",
    category: "converter",
    icon: "Dice5",
    tags: ["random", "number", "dice", "lottery", "generate", "range"],
    usageCount: 890_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-dedupe",
    slug: "remove-duplicates",
    name: "Remove Duplicate Lines",
    description: "Remove duplicate lines from any text. Sort lines alphabetically, count duplicates, and keep only unique lines. Perfect for cleaning up data and lists.",
    shortDescription: "Remove duplicate lines from text instantly.",
    category: "converter",
    icon: "ListFilter",
    tags: ["duplicate", "remove", "unique", "lines", "sort", "clean", "list"],
    usageCount: 340_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── More AI Writing Tools ─────────────────────
  {
    id: "ai-hashtag",
    slug: "hashtag-gen",
    name: "AI Hashtag Generator",
    description: "Generate trending hashtags for Instagram, TikTok, Twitter, and LinkedIn. Enter your topic or upload an image to get 30+ relevant hashtags sorted by popularity.",
    shortDescription: "Generate trending hashtags for social media.",
    category: "ai-writing",
    icon: "Hash",
    tags: ["hashtag", "instagram", "tiktok", "twitter", "social media", "trending"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_300_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter your topic", description: "Type your post topic, niche, or content description." },
      { title: "Select platform", description: "Choose Instagram, TikTok, Twitter/X, or LinkedIn for platform-optimized hashtags." },
      { title: "Copy hashtags", description: "Get 30+ relevant hashtags sorted by reach. Copy all or select individual hashtags." },
    ],
  },
  {
    id: "ai-story",
    slug: "story-generator",
    name: "AI Story Generator",
    description: "Generate short stories, creative fiction, or narrative content with AI. Set the genre, characters, setting, and length — get a complete story in seconds.",
    shortDescription: "Generate creative stories with AI.",
    category: "ai-writing",
    icon: "BookOpen",
    tags: ["story", "creative writing", "fiction", "narrative", "short story", "ai"],
    isNew: true,
    isFeatured: true,
    usageCount: 640_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Set the scene", description: "Choose genre (romance, thriller, comedy, fantasy etc.), describe characters, and set the scene." },
      { title: "Choose length", description: "Select flash fiction (100 words), short story (500 words), or extended story (1000+ words)." },
      { title: "Get your story", description: "AI generates a complete story with beginning, middle, and end. Edit, copy, or regenerate." },
    ],
  },
  {
    id: "ai-business-name",
    slug: "business-name",
    name: "Business Name Generator",
    description: "Generate creative and catchy business names for your startup or brand. Enter keywords describing your business and get 20+ unique name ideas with domain availability hints.",
    shortDescription: "Generate creative business names with AI.",
    category: "ai-writing",
    icon: "Building2",
    tags: ["business name", "brand name", "startup", "company name", "domain", "branding"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 720_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Describe your business", description: "Enter keywords about your business type, industry, values, and target audience." },
      { title: "Choose name style", description: "Pick from Creative, Professional, Catchy, Technical, or Minimal name styles." },
      { title: "Pick your name", description: "Get 20+ unique business name suggestions. Short, memorable, and brandable." },
    ],
  },

  // ── Image Special Effects ──────────────────────────────────────
  {
    id: "image-blur",
    slug: "blur-image",
    name: "Blur Image",
    description: "Apply blur effects to entire images. Choose from Gaussian blur, motion blur, or soft focus. Perfect for backgrounds and creative effects.",
    shortDescription: "Blur images with various blur effects.",
    category: "image",
    icon: "Blend",
    tags: ["blur", "gaussian", "effect", "soften", "privacy"],
    usageCount: 540_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-pixel-art",
    slug: "pixel-art",
    name: "Picture to Pixel Art",
    description: "Convert any photo into retro pixel art style. Adjust pixel size to create the perfect 8-bit or 16-bit style pixelated image.",
    shortDescription: "Convert photos to pixel art style.",
    category: "image",
    icon: "Grid2x2",
    tags: ["pixel art", "retro", "8-bit", "16-bit", "game", "convert"],
    isNew: true,
    isFeatured: true,
    usageCount: 870_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-add-logo",
    slug: "add-logo",
    name: "Add Logo to Image",
    description: "Add your logo or watermark to images in bulk. Control position, size, and opacity. Perfect for branding product photos and social media content.",
    shortDescription: "Add logo or watermark to images in bulk.",
    category: "image",
    icon: "Layers",
    tags: ["logo", "watermark", "brand", "bulk", "overlay"],
    usageCount: 680_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },

  // ── Image Basic Editing ────────────────────────────────────────
  {
    id: "image-split",
    slug: "split-image",
    name: "Split Image",
    description: "Split images into multiple equal parts horizontally or vertically. Create Instagram carousel grids by splitting a wide image into 3, 6, or 9 squares.",
    shortDescription: "Split image into grid or multiple parts.",
    category: "image",
    icon: "SplitSquareHorizontal",
    tags: ["split", "divide", "grid", "instagram", "carousel"],
    isNew: true,
    isFeatured: true,
    usageCount: 760_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-remove-metadata",
    slug: "remove-metadata",
    name: "Remove Metadata",
    description: "Strip EXIF metadata from images for privacy. Remove GPS location, camera settings, date, and personal info from photos before sharing.",
    shortDescription: "Remove EXIF metadata from images for privacy.",
    category: "image",
    icon: "ShieldOff",
    tags: ["metadata", "exif", "privacy", "gps", "remove", "strip"],
    isNew: true,
    usageCount: 420_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".tiff"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-view-metadata",
    slug: "view-metadata",
    name: "View Image Metadata",
    description: "View all EXIF metadata stored in your image files. See camera model, GPS coordinates, date taken, ISO, aperture, shutter speed, and more.",
    shortDescription: "View EXIF metadata stored in image files.",
    category: "image",
    icon: "Info",
    tags: ["metadata", "exif", "view", "gps", "camera", "info"],
    usageCount: 280_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".tiff"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-reduce-kb",
    slug: "reduce-kb",
    name: "Reduce Image Size in KB",
    description: "Compress images to an exact file size in KB. Specify a target size like 100KB, 200KB, or 500KB and get your image compressed to exactly that size.",
    shortDescription: "Compress image to exact KB size you want.",
    category: "image",
    icon: "FileDown",
    tags: ["reduce size", "compress", "kb", "file size", "exact size"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 2_400_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-increase-kb",
    slug: "increase-kb",
    name: "Increase Image Size in KB",
    description: "Increase image file size to meet minimum upload requirements. Specify a target size and pad the image to meet that requirement without visible quality loss.",
    shortDescription: "Increase image file size to meet requirements.",
    category: "image",
    icon: "FileUp",
    tags: ["increase size", "file size", "kb", "minimum", "requirement"],
    usageCount: 380_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png"],
    maxFileSizeMB: 10,
    maxFiles: 5,
  },
  {
    id: "image-resize-cm",
    slug: "resize-cm",
    name: "Resize Image in Centimeters",
    description: "Resize images to exact centimeter dimensions. Set DPI/resolution for print-quality output. Perfect for printing and document photos.",
    shortDescription: "Resize images to exact cm dimensions for print.",
    category: "image",
    icon: "Ruler",
    tags: ["resize", "centimeter", "cm", "print", "dpi", "dimensions"],
    usageCount: 580_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-resize-passport",
    slug: "resize-3-5-cm",
    name: "Resize Image (3.5×4.5cm)",
    description: "Resize photos to standard passport/ID size of 3.5cm x 4.5cm at 300 DPI. Perfect for visa applications, ID cards, and government documents.",
    shortDescription: "Resize photo to 3.5×4.5cm passport size.",
    category: "image",
    icon: "CreditCard",
    tags: ["passport", "3.5cm", "4.5cm", "id card", "visa", "resize"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 3_200_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 10,
    maxFiles: 10,
  },
  // ── Social Media Image Tools ───────────────────────────────────
  {
    id: "image-social-resize",
    slug: "social-resize",
    name: "Social Media Image Resizer",
    description: "Resize images for all social media platforms. Presets for Instagram (Post/Story/Reel), Facebook, Twitter/X, LinkedIn, YouTube, TikTok, and more.",
    shortDescription: "Resize images for all social media sizes.",
    category: "image",
    icon: "Share2",
    tags: ["social media", "instagram", "facebook", "twitter", "resize", "post"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 2_600_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  // ── More PDF Tools ──────────────────────────────────────────────
  {
    id: "pdf-excel-to-pdf",
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert Excel spreadsheets (.xlsx, .xls) to PDF. Preserves formatting, tables, charts, and layout. Make your spreadsheets easy to read and share.",
    shortDescription: "Convert Excel spreadsheets to PDF.",
    category: "pdf",
    icon: "TableProperties",
    tags: ["excel", "xlsx", "xls", "convert", "spreadsheet"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_400_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [".xlsx", ".xls", ".csv"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },
  {
    id: "pdf-edit",
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Add text, images, shapes, and annotations to PDF documents. Edit the size, font, and color of added content. Draw and annotate freely.",
    shortDescription: "Add text, images, and annotations to PDF.",
    category: "pdf",
    icon: "FileEdit",
    tags: ["edit", "annotate", "text", "draw", "shapes"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 2_100_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-html-to-pdf",
    slug: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert webpages or HTML code to PDF. Enter a URL or paste HTML to get a perfectly rendered PDF. Preserves layout, images, and styling.",
    shortDescription: "Convert HTML or webpage URL to PDF.",
    category: "pdf",
    icon: "Globe",
    tags: ["html", "webpage", "url", "convert", "web"],
    isNew: true,
    isFeatured: true,
    usageCount: 780_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "pdf-organize",
    slug: "organize-pdf",
    name: "Organize PDF",
    description: "Rearrange, delete, and add pages to your PDF. Drag and drop pages to reorder them. Extract specific pages or add blank pages anywhere.",
    shortDescription: "Rearrange, delete, and add PDF pages.",
    category: "pdf",
    icon: "LayoutList",
    tags: ["organize", "reorder", "pages", "delete", "rearrange"],
    isNew: true,
    isFeatured: true,
    usageCount: 560_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-repair",
    slug: "repair-pdf",
    name: "Repair PDF",
    description: "Repair damaged or corrupt PDF files. Recover data from PDF files that won't open or display errors. Fix broken PDF structure automatically.",
    shortDescription: "Repair damaged and corrupt PDF files.",
    category: "pdf",
    icon: "Wrench",
    tags: ["repair", "fix", "corrupt", "damaged", "recover"],
    usageCount: 340_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 5,
  },
  {
    id: "pdf-to-text",
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract all text content from your PDF and download it as a clean .txt file. Preserves paragraph structure and page breaks. Works with any PDF.",
    shortDescription: "Extract text from PDF as .txt file.",
    category: "pdf",
    icon: "FileText",
    acceptedFileTypes: [".pdf"],
    maxFiles: 5,
    maxFileSizeMB: 50,
    tags: ["extract text", "pdf to txt", "copy text"],
  },
  {
    id: "pdf-header-footer",
    slug: "header-footer",
    name: "Add Header / Footer",
    description: "Add custom header or footer text to every page of your PDF. Choose font size, position, and text. Perfect for adding document titles, dates, or page numbers.",
    shortDescription: "Add custom header or footer to PDF pages.",
    category: "pdf",
    icon: "AlignCenter",
    acceptedFileTypes: [".pdf"],
    maxFiles: 5,
    maxFileSizeMB: 50,
    tags: ["header", "footer", "add text", "pdf"],
  },
  {
    id: "pdf-compare",
    slug: "compare-pdf",
    name: "Compare PDF",
    description: "Compare two PDF documents side by side. Spot differences, changes, and modifications between different versions of a document with highlights.",
    shortDescription: "Compare two PDFs to find differences.",
    category: "pdf",
    icon: "GitCompare",
    tags: ["compare", "diff", "differences", "version", "changes"],
    isNew: true,
    isFeatured: true,
    usageCount: 420_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 2,
  },
  {
    id: "pdf-redact",
    slug: "redact-pdf",
    name: "Redact PDF",
    description: "Permanently redact (black out) sensitive text and images from PDF documents. Securely remove confidential information before sharing documents.",
    shortDescription: "Permanently redact sensitive info from PDF.",
    category: "pdf",
    icon: "EyeOff",
    tags: ["redact", "sensitive", "confidential", "black out", "privacy"],
    isNew: true,
    isFeatured: true,
    usageCount: 290_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-crop",
    slug: "crop-pdf",
    name: "Crop PDF",
    description: "Crop margins of PDF documents or select specific page areas to keep. Apply crop changes to one page, selected pages, or all pages at once.",
    shortDescription: "Crop PDF margins and page areas.",
    category: "pdf",
    icon: "Crop",
    tags: ["crop", "margins", "trim", "page area", "cut"],
    usageCount: 380_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-scan",
    slug: "scan-to-pdf",
    name: "Scan to PDF",
    description: "Convert scanned images and photos to searchable PDF documents. Upload photos of documents, receipts, or books and get a clean, searchable PDF.",
    shortDescription: "Convert scanned images to searchable PDF.",
    category: "pdf",
    icon: "ScanLine",
    tags: ["scan", "scanned", "image to pdf", "searchable", "document"],
    isNew: true,
    usageCount: 670_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".tiff", ".bmp"],
    maxFileSizeMB: 50,
    maxFiles: 20,
  },
  {
    id: "pdf-pdfa",
    slug: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    description: "Convert PDFs to PDF/A format for long-term archiving. The ISO-standardized PDF/A ensures your documents are preserved and accessible in the future.",
    shortDescription: "Convert PDF to PDF/A archival format.",
    category: "pdf",
    icon: "Archive",
    tags: ["pdf/a", "archive", "iso", "long-term", "preservation"],
    usageCount: 180_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 5,
  },
  {
    id: "pdf-translate",
    slug: "translate-pdf",
    name: "Translate PDF",
    description: "AI-powered PDF translation. Upload a PDF and select the target language — get a fully translated PDF that preserves the original layout and formatting.",
    shortDescription: "Translate PDF files with AI layout preservation.",
    category: "pdf",
    icon: "Languages",
    tags: ["translate", "ai", "language", "multilingual", "document"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_600_000,
    estimatedTime: "~30s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 3,
  },
  {
    id: "pdf-ai-summarize",
    slug: "summarize-pdf",
    name: "AI PDF Summarizer",
    description: "Upload any PDF and get an AI-generated summary. Extract key points, main ideas, and conclusions from long documents in seconds. Supports any language.",
    shortDescription: "Summarize any PDF document with AI.",
    category: "pdf",
    icon: "FileSearch",
    tags: ["summarize", "ai", "summary", "extract", "key points"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_200_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 3,
  },

  // ── Note Maker & Article Writer ──────────────
  {
    id: "ai-note-maker",
    slug: "note-maker",
    name: "AI Note Maker",
    description: "Create organized study notes from any topic. Choose bullet points, outlines, or Cornell notes format. Supports Hindi, Urdu, English and more languages.",
    shortDescription: "Generate organized notes on any topic.",
    category: "ai-writing",
    icon: "NotebookPen",
    tags: ["notes", "study", "study notes", "outline", "learning", "education"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_400_000,
    estimatedTime: "~4s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter a topic", description: "Type any subject — a chapter, concept, topic, or event you need notes on." },
      { title: "Choose format & language", description: "Select bullet points, numbered list, outline, or Cornell notes. Choose from 7 languages." },
      { title: "Get instant notes", description: "Get well-organized, easy-to-study notes in seconds. Copy or download them." },
    ],
  },
  {
    id: "ai-article-writer",
    slug: "article-writer",
    name: "AI Article Writer",
    description: "Write complete articles on any topic with AI. Set the tone, word count, language, and sections. Get SEO-optimized, well-structured articles instantly.",
    shortDescription: "Write complete articles with AI in any language.",
    category: "ai-writing",
    icon: "Newspaper",
    tags: ["article", "writing", "content", "blog", "SEO", "journalism"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 920_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter article topic", description: "Type your topic, issue, or subject for the article." },
      { title: "Set parameters", description: "Choose tone (Informative/Persuasive/Academic), word count (300–2000), and language." },
      { title: "Get the article", description: "Get a complete article with intro, sections, and conclusion. Copy or download." },
    ],
  },

  // ── Funny / Fun Tools ─────────────────────────
  {
    id: "ai-roast",
    slug: "roast-gen",
    name: "Roast Generator",
    description: "Generate funny, lighthearted roasts for your friends. Enter their name and quirky traits — get hilarious roast lines perfect for parties and friend groups.",
    shortDescription: "Generate funny friendly roasts with AI.",
    category: "ai-writing",
    icon: "Flame",
    tags: ["roast", "funny", "humor", "friends", "comedy", "fun"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_200_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter the name", description: "Type the name of the person you want to roast." },
      { title: "Add their quirks", description: "Optionally add their funny habits or traits for personalized roasts." },
      { title: "Get the roast", description: "Get 5-7 funny, friendly roast lines that will make everyone laugh." },
    ],
  },
  {
    id: "ai-dad-jokes",
    slug: "dad-jokes",
    name: "Dad Joke Generator",
    description: "Generate groan-worthy dad jokes on any topic. Perfect for breaking the ice, making kids laugh, or annoying your family. The worse, the better!",
    shortDescription: "Generate groan-worthy dad jokes instantly.",
    category: "ai-writing",
    icon: "Smile",
    tags: ["dad joke", "funny", "humor", "comedy", "jokes", "puns"],
    isNew: true,
    isPopular: true,
    usageCount: 880_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-emoji-translator",
    slug: "emoji-translator",
    name: "Emoji Translator",
    description: "Translate any text into emojis! Convert sentences into emoji-based messages for fun social media posts, messages, and stories.",
    shortDescription: "Translate text into emojis instantly.",
    category: "ai-writing",
    icon: "Smile",
    tags: ["emoji", "fun", "translate", "social media", "funny", "creative"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 760_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-shakespeare",
    slug: "shakespeare",
    name: "Shakespeare Translator",
    description: "Translate modern English into dramatic Shakespearean style. Turn everyday sentences into thee, thou, hath, dost — perfect for fun and theatre lovers.",
    shortDescription: "Translate text into Shakespearean English.",
    category: "ai-writing",
    icon: "BookOpen",
    tags: ["shakespeare", "old english", "funny", "drama", "theater", "fun"],
    isNew: true,
    usageCount: 540_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-corporate-jargon",
    slug: "corporate-jargon",
    name: "Corporate Jargon Generator",
    description: "Turn simple sentences into confusing corporate buzzword soup. Synergize your bandwidth to leverage this paradigm-shifting solution for maximum ROI!",
    shortDescription: "Convert simple text to corporate buzzword speak.",
    category: "ai-writing",
    icon: "Briefcase",
    tags: ["corporate", "buzzwords", "funny", "office humor", "business", "meme"],
    isNew: true,
    isPopular: true,
    usageCount: 490_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── More Funny Tools ─────────────────────────
  {
    id: "ai-fortune-cookie",
    slug: "fortune-cookie",
    name: "Fortune Cookie",
    description: "Get AI-generated fortune cookie wisdom with a twist of humor. Click for your daily fortune — mysterious, funny, and oddly accurate predictions await!",
    shortDescription: "Get random fortune cookie wisdom with AI.",
    category: "ai-writing",
    icon: "Cookie",
    tags: ["fortune", "funny", "wisdom", "prediction", "fun", "daily"],
    isNew: true,
    isPopular: true,
    usageCount: 320_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-excuse-gen",
    slug: "excuse-gen",
    name: "Excuse Generator",
    description: "Generate creative, funny excuses for being late, missing homework, skipping meetings, or any awkward situation. Powered by AI, believable by design!",
    shortDescription: "Generate hilarious excuses for any situation.",
    category: "ai-writing",
    icon: "MessageSquareWarning",
    tags: ["excuse", "funny", "humor", "late", "homework", "fun", "creative"],
    isNew: true,
    isPopular: true,
    usageCount: 410_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-compliment-gen",
    slug: "compliment-gen",
    name: "Compliment Generator",
    description: "Generate funny, cheesy, sweet, or savage compliments for friends, crushes, or coworkers. Pick your vibe and spread the good vibes instantly!",
    shortDescription: "Generate funny and sweet compliments instantly.",
    category: "ai-writing",
    icon: "Heart",
    tags: ["compliment", "funny", "sweet", "friends", "social", "fun", "kind"],
    isNew: true,
    isFeatured: true,
    usageCount: 280_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "poem-gen",
    name: "Poem Generator",
    slug: "poem-gen",
    category: "ai-writing",
    icon: "Feather",
    tags: ["poem", "poetry", "creative writing", "haiku", "sonnet", "limerick"],
    description: "Generate beautiful poems on any topic. Choose from haiku, sonnet, free verse, limerick, and more. Set the mood and let AI craft the perfect poem for you.",
    shortDescription: "Generate beautiful poems on any topic with AI.",
    acceptedFileTypes: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    isNew: true,
    isPopular: false,
    isPremium: false,
  },
  {
    id: "song-lyrics",
    name: "Song Lyrics Generator",
    slug: "song-lyrics",
    category: "ai-writing",
    icon: "Music",
    tags: ["song lyrics", "music", "rap", "pop", "ballad", "songwriting", "creative"],
    description: "Generate original song lyrics for any genre — pop, rap, ballad, country, R&B, and more. Enter your theme or story and get complete lyrics with verses, chorus, and bridge.",
    shortDescription: "Generate original song lyrics for any genre.",
    acceptedFileTypes: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    isNew: true,
    isPopular: true,
    isPremium: false,
  },
  {
    id: "tagline-gen",
    name: "Tagline Generator",
    slug: "tagline-gen",
    category: "ai-writing",
    icon: "Tag",
    tags: ["tagline", "slogan", "brand", "marketing", "catchphrase", "branding"],
    description: "Generate catchy taglines and slogans for your brand, product, or campaign. Get 10 unique options with different tones — bold, witty, inspirational, minimal.",
    shortDescription: "Generate catchy taglines and slogans for your brand.",
    acceptedFileTypes: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    isNew: true,
    isPopular: false,
    isPremium: false,
  },
  {
    id: "speech-writer",
    name: "Speech Writer",
    slug: "speech-writer",
    category: "ai-writing",
    icon: "Mic",
    tags: ["speech", "wedding", "graduation", "farewell", "award", "presentation", "public speaking"],
    description: "Write powerful speeches for weddings, graduations, farewells, award ceremonies, and more. Personalize with names, stories, and tone to create a memorable, heartfelt speech.",
    shortDescription: "Write speeches for weddings, graduations, and events.",
    acceptedFileTypes: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    isNew: true,
    isPopular: false,
    isPremium: false,
  },
  {
    id: "cold-dm",
    name: "Cold DM Generator",
    slug: "cold-dm",
    category: "ai-writing",
    icon: "Send",
    tags: ["cold dm", "outreach", "instagram", "linkedin", "sales", "networking", "message"],
    description: "Write personalized cold DMs and outreach messages for Instagram, LinkedIn, Twitter, and email. Generate non-spammy, conversion-focused messages that actually get replies.",
    shortDescription: "Write cold outreach messages that get replies.",
    acceptedFileTypes: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    isNew: true,
    isPopular: true,
    isPremium: false,
  },
];

// ─────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────

export function getToolBySlug(slug: string, category: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug && t.category === category);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getFeaturedTools(limit = 8): Tool[] {
  return TOOLS.filter((t) => t.isFeatured)
    .sort((a, b) => (b.usageCount ?? 0) - (a.usageCount ?? 0))
    .slice(0, limit);
}

export function getPopularTools(limit = 12): Tool[] {
  return TOOLS.filter((t) => t.isPopular)
    .sort((a, b) => (b.usageCount ?? 0) - (a.usageCount ?? 0))
    .slice(0, limit);
}

export { TOOL_CATEGORIES } from "@/config/navigation";
