import type { Tool, ToolCategory } from "@/types";

// ─────────────────────────────────────────────
// Tool registry
// In production this comes from a database/CMS.
// This file is the static type-safe fallback and
// source of truth for generateStaticParams.
// ─────────────────────────────────────────────

export const TOOLS: Tool[] = [
  // ── PDF Tools ──────────────────────────────
  {
    id: "pdf-compress",
    slug: "compress",
    name: "Compress PDF",
    description:
      "Reduce PDF file size while maintaining quality. Supports batch compression of multiple files at once with smart optimization.",
    shortDescription: "Reduce PDF file size without losing quality.",
    category: "pdf",
    icon: "FileDown",
    tags: ["compress", "optimize", "reduce size"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_400_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 20,
  },
  {
    id: "pdf-merge",
    slug: "merge",
    name: "Merge PDF",
    description:
      "Combine multiple PDF files into one. Drag to reorder pages before merging for precise document control.",
    shortDescription: "Combine multiple PDFs into one document.",
    category: "pdf",
    icon: "Combine",
    tags: ["merge", "combine", "join"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_800_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 50,
  },
  {
    id: "pdf-split",
    slug: "split",
    name: "Split PDF",
    description: "Split a PDF into individual pages or custom page ranges. Extract exactly what you need.",
    shortDescription: "Split PDF into individual pages or ranges.",
    category: "pdf",
    icon: "Scissors",
    tags: ["split", "separate", "extract pages"],
    usageCount: 980_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-to-word",
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF documents to editable Word (.docx) files with AI-powered layout preservation.",
    shortDescription: "Convert PDF to editable Word document.",
    category: "pdf",
    icon: "FileEdit",
    tags: ["convert", "word", "docx", "editable"],
    isNew: true,
    isFeatured: true,
    usageCount: 650_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },
  {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert each PDF page into high-quality JPG images. Choose resolution and quality settings.",
    shortDescription: "Convert PDF pages to JPG images.",
    category: "pdf",
    icon: "Image",
    tags: ["convert", "jpg", "image", "export"],
    usageCount: 870_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 10,
  },
  {
    id: "pdf-rotate",
    slug: "rotate",
    name: "Rotate PDF",
    description: "Rotate individual pages or the entire PDF document. Fix incorrectly scanned documents in seconds.",
    shortDescription: "Rotate PDF pages to correct orientation.",
    category: "pdf",
    icon: "RotateCw",
    tags: ["rotate", "orientation", "fix"],
    usageCount: 420_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },

  // ── Image Tools ─────────────────────────────
  {
    id: "image-compress",
    slug: "compress",
    name: "Compress Image",
    description: "Compress JPEG, PNG, WebP images up to 90% smaller with no visible quality loss using smart AI compression.",
    shortDescription: "Compress images without visible quality loss.",
    category: "image",
    icon: "ImageDown",
    tags: ["compress", "optimize", "reduce size"],
    isPopular: true,
    isFeatured: true,
    usageCount: 3_200_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
    maxFileSizeMB: 25,
    maxFiles: 30,
  },
  {
    id: "image-resize",
    slug: "resize",
    name: "Resize Image",
    description: "Resize images to exact pixel dimensions or percentage. Maintain aspect ratio with smart crop options.",
    shortDescription: "Resize images to any dimension.",
    category: "image",
    icon: "Scaling",
    tags: ["resize", "dimensions", "scale"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_500_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-bg-remove",
    slug: "remove-background",
    name: "Remove Background",
    description: "AI-powered background removal. Get transparent PNG in seconds. Perfect for product photos and portraits.",
    shortDescription: "Remove image background with AI instantly.",
    category: "image",
    icon: "Eraser",
    tags: ["background removal", "transparent", "AI"],
    isNew: true,
    isFeatured: true,
    usageCount: 2_100_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 10,
    maxFiles: 5,
  },
  {
    id: "image-convert",
    slug: "convert",
    name: "Convert Image",
    description: "Convert between JPG, PNG, WebP, AVIF, GIF and more. Batch convert hundreds of images at once.",
    shortDescription: "Convert between all image formats.",
    category: "image",
    icon: "ArrowRightLeft",
    tags: ["convert", "format", "jpg", "png", "webp"],
    usageCount: 780_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp", ".tiff"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },

  // ── Video Tools ─────────────────────────────
  {
    id: "video-compress",
    slug: "compress",
    name: "Compress Video",
    description: "Reduce video file size with minimal quality loss. Supports MP4, MOV, AVI, WebM with H.264/H.265 encoding.",
    shortDescription: "Compress video files without quality loss.",
    category: "video",
    icon: "VideoOff",
    tags: ["compress", "reduce size", "MP4"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_200_000,
    estimatedTime: "~30s",
    acceptedFileTypes: [".mp4", ".mov", ".avi", ".webm", ".mkv"],
    maxFileSizeMB: 500,
    maxFiles: 3,
  },
  // ── AI Writing ──────────────────────────────
  {
    id: "ai-summarize",
    slug: "summarize",
    name: "AI Summarizer",
    description: "Summarize long articles, documents, or text into clear bullet points or concise paragraphs with one click.",
    shortDescription: "Summarize any text with AI in seconds.",
    category: "ai-writing",
    icon: "AlignLeft",
    tags: ["summarize", "condense", "abstract"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_600_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-translate",
    slug: "translate",
    name: "AI Translator",
    description: "Translate text between 100+ languages with context-aware AI translation that preserves tone and meaning.",
    shortDescription: "Translate text into 100+ languages.",
    category: "ai-writing",
    icon: "Languages",
    tags: ["translate", "language", "localize"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_300_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-rewrite",
    slug: "rewrite",
    name: "AI Rewriter",
    description: "Rewrite any text to improve clarity, tone, or style. Choose from professional, casual, formal, or creative modes.",
    shortDescription: "Rewrite text to improve clarity and tone.",
    category: "ai-writing",
    icon: "RefreshCw",
    tags: ["rewrite", "paraphrase", "rephrase"],
    isNew: true,
    usageCount: 740_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-grammar",
    slug: "grammar-check",
    name: "Grammar Checker",
    description: "Fix grammar, spelling, and punctuation errors instantly. Get detailed explanations for every correction made.",
    shortDescription: "Check and fix grammar errors with AI.",
    category: "ai-writing",
    icon: "SpellCheck",
    tags: ["grammar", "spell check", "proofread"],
    usageCount: 1_100_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── More PDF Tools ──────────────────────────
  {
    id: "pdf-unlock",
    slug: "unlock",
    name: "Unlock PDF",
    description: "Remove password protection from PDF files. Instantly unlock encrypted PDFs for editing and printing.",
    shortDescription: "Remove password protection from PDF.",
    category: "pdf",
    icon: "LockOpen",
    tags: ["unlock", "password", "remove protection"],
    isNew: true,
    usageCount: 430_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 5,
  },
  {
    id: "pdf-protect",
    slug: "protect",
    name: "Protect PDF",
    description: "Add password protection to PDF files. Set open password and permission restrictions to secure sensitive documents.",
    shortDescription: "Add password protection to PDF.",
    category: "pdf",
    icon: "Lock",
    tags: ["protect", "password", "secure", "encrypt"],
    usageCount: 280_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 5,
  },
  {
    id: "pdf-watermark",
    slug: "watermark",
    name: "Add Watermark",
    description: "Add text or image watermarks to PDF documents. Customize position, opacity, font, and color.",
    shortDescription: "Add watermark text or logo to PDF.",
    category: "pdf",
    icon: "Stamp",
    tags: ["watermark", "stamp", "brand", "protect"],
    usageCount: 310_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 10,
  },
  {
    id: "pdf-to-excel",
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Convert PDF tables and data into editable Excel spreadsheets (.xlsx) with AI-powered table detection.",
    shortDescription: "Convert PDF tables to Excel spreadsheet.",
    category: "pdf",
    icon: "TableProperties",
    tags: ["convert", "excel", "xlsx", "table"],
    isNew: true,
    usageCount: 520_000,
    estimatedTime: "~12s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },
  {
    id: "pdf-sign",
    slug: "sign",
    name: "Sign PDF",
    description: "Add digital signatures to PDF files. Draw, type, or upload your signature and place it anywhere.",
    shortDescription: "Add digital signature to PDF.",
    category: "pdf",
    icon: "PenLine",
    tags: ["sign", "signature", "esign", "digital"],
    isFeatured: true,
    isNew: true,
    usageCount: 680_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 50,
    maxFiles: 1,
  },
  {
    id: "pdf-page-numbers",
    slug: "page-numbers",
    name: "Add Page Numbers",
    description: "Add customizable page numbers to PDF documents. Choose position, font, size, start number, and format.",
    shortDescription: "Add page numbers to PDF documents.",
    category: "pdf",
    icon: "Hash",
    tags: ["page numbers", "numbering", "footer", "header"],
    usageCount: 190_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "pdf-ocr",
    slug: "ocr",
    name: "PDF OCR",
    description: "Extract text from scanned PDFs and images using AI-powered OCR. Converts scanned documents into searchable, editable text. Supports 40+ languages.",
    shortDescription: "Extract text from scanned PDFs with OCR.",
    category: "pdf",
    icon: "ScanText",
    tags: ["ocr", "scan", "extract text", "scanned", "searchable"],
    isNew: true,
    isFeatured: true,
    usageCount: 390_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".pdf", ".jpg", ".jpeg", ".png", ".tiff"],
    maxFileSizeMB: 50,
    maxFiles: 5,
  },

  {
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG, PNG, or WebP images to a single PDF. Drag to reorder, choose page size and margins.",
    shortDescription: "Convert images to a PDF document.",
    category: "pdf",
    icon: "FileImage",
    tags: ["jpg", "image", "convert", "create pdf"],
    isPopular: true,
    usageCount: 1_100_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 50,
  },

  // ── More Image Tools ─────────────────────────
  {
    id: "image-thumbnail-creator",
    slug: "thumbnail-creator",
    name: "AI Thumbnail Creator",
    description: "Describe your thumbnail idea and AI generates it instantly. Upload your own photo to include yourself in the thumbnail. Supports YouTube, Instagram, Twitter/X, and more.",
    shortDescription: "Describe your idea, AI creates your thumbnail.",
    category: "image",
    icon: "Sparkles",
    tags: ["thumbnail", "ai", "youtube", "instagram", "generate", "design"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 850_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 10,
    maxFiles: 1,
    howItWorks: [
      { title: "Describe your thumbnail", description: "Type what you want — e.g. 'Gaming thumbnail with fire effects and my photo in the corner'. The more detail, the better." },
      { title: "Upload your photo (optional)", description: "Drop in your own photo and it will be layered into the generated thumbnail automatically." },
      { title: "Generate & download", description: "Click Generate to create your thumbnail. Adjust style, text, and colors, then download in full resolution." },
    ],
  },
  {
    id: "image-crop",
    slug: "crop",
    name: "Crop Image",
    description: "Crop images to exact dimensions or aspect ratios. Supports free crop, fixed ratios (1:1, 16:9, 4:3), and custom pixel crops.",
    shortDescription: "Crop images to any size or ratio.",
    category: "image",
    icon: "Crop",
    tags: ["crop", "trim", "resize", "aspect ratio"],
    isPopular: true,
    usageCount: 1_200_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-watermark",
    slug: "watermark",
    name: "Image Watermark",
    description: "Add text or logo watermarks to images. Customize opacity, position, size, and font. Batch process multiple images.",
    shortDescription: "Add text or logo watermark to images.",
    category: "image",
    icon: "Stamp",
    tags: ["watermark", "logo", "brand", "protect"],
    usageCount: 390_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-to-pdf",
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert one or multiple images to a single PDF file. Supports JPG, PNG, WebP. Customize page size and margins.",
    shortDescription: "Convert images to PDF in one click.",
    category: "image",
    icon: "FilePlus",
    tags: ["convert", "pdf", "jpg", "png"],
    usageCount: 720_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 50,
    maxFiles: 30,
  },
  {
    id: "qr-code-generator",
    slug: "qr-code",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, Wi-Fi, vCard, and more. Customize colors, size, and download as PNG or SVG.",
    shortDescription: "Generate custom QR codes instantly.",
    category: "image",
    icon: "QrCode",
    tags: ["qr code", "generator", "url", "barcode"],
    isNew: true,
    isFeatured: true,
    usageCount: 1_400_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "image-upscale",
    slug: "upscale",
    name: "AI Image Upscaler",
    description: "Upscale images 2x or 4x using AI super-resolution. Enhances details and sharpness without pixelation.",
    shortDescription: "Upscale images 2x–4x with AI.",
    category: "image",
    icon: "Maximize2",
    tags: ["upscale", "enhance", "AI", "resolution", "super resolution"],
    isFeatured: true,
    isNew: true,
    usageCount: 960_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 10,
    maxFiles: 5,
  },
  {
    id: "meme-generator",
    slug: "meme",
    name: "Meme Generator",
    description: "Create memes with popular templates or upload your own image. Add top and bottom text with custom fonts and colors.",
    shortDescription: "Create memes with templates or custom images.",
    category: "image",
    icon: "Smile",
    tags: ["meme", "fun", "text", "social media"],
    isNew: true,
    usageCount: 450_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },

  // ── Image Effects (new) ────────────────────
  {
    id: "image-black-white",
    slug: "black-white",
    name: "Photo Black & White",
    shortDescription: "Convert any photo to black & white instantly.",
    description: "Convert photos to stunning black and white with adjustable contrast and brightness controls.",
    category: "image",
    icon: "Circle",
    tags: ["black white", "grayscale", "monochrome", "filter"],
    usageCount: 890_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-pixelate",
    slug: "pixelate",
    name: "Pixelate Image",
    shortDescription: "Pixelate or censor parts of an image with a brush.",
    description: "Paint over areas to pixelate or blur for privacy, artistic effects, or censoring sensitive content.",
    category: "image",
    icon: "Grid3x3",
    tags: ["pixelate", "censor", "privacy", "blur"],
    usageCount: 320_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-blur-bg",
    slug: "blur-background",
    name: "Blur Background",
    shortDescription: "Blur the background of any photo automatically.",
    description: "Create stunning portrait-mode blur effects by automatically detecting and blurring the background.",
    category: "image",
    icon: "Blend",
    tags: ["blur", "background", "portrait", "bokeh"],
    usageCount: 680_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 5,
  },
  {
    id: "image-cleanup",
    slug: "cleanup",
    name: "Cleanup Picture",
    shortDescription: "Remove unwanted objects from photos with a brush.",
    description: "Paint over any object with a brush to remove it. Perfect for removing blemishes, objects, and distractions from photos.",
    category: "image",
    icon: "Eraser",
    tags: ["cleanup", "remove objects", "inpaint", "retouch"],
    isNew: true,
    isFeatured: true,
    usageCount: 760_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-rotate",
    slug: "rotate",
    name: "Rotate Image",
    shortDescription: "Rotate images 90°, 180°, or any custom angle.",
    description: "Rotate images clockwise or counter-clockwise by 90°, 180°, 270°, or any custom angle.",
    category: "image",
    icon: "RotateCw",
    tags: ["rotate", "turn", "angle", "orientation"],
    usageCount: 520_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-flip",
    slug: "flip",
    name: "Image Flipper",
    shortDescription: "Flip or mirror images horizontally or vertically.",
    description: "Instantly flip or mirror images horizontally (left-right) or vertically (top-bottom).",
    category: "image",
    icon: "FlipHorizontal",
    tags: ["flip", "mirror", "horizontal", "vertical"],
    usageCount: 440_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
    maxFileSizeMB: 25,
    maxFiles: 20,
  },
  {
    id: "image-add-border",
    slug: "add-border",
    name: "Add Border to Image",
    shortDescription: "Add a custom border or frame to any image.",
    description: "Add custom colored borders and frames to images. Choose border width, color, and style.",
    category: "image",
    icon: "Square",
    tags: ["border", "frame", "edge", "decorate"],
    usageCount: 280_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-round",
    slug: "round-image",
    name: "Make Image Round",
    shortDescription: "Crop images into circle or rounded shapes.",
    description: "Convert any image into a perfect circle or rounded rectangle. Great for profile photos and logos.",
    category: "image",
    icon: "CircleDot",
    tags: ["round", "circle", "crop", "profile photo"],
    usageCount: 390_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 10,
  },
  {
    id: "image-combine",
    slug: "combine",
    name: "Combine Images",
    shortDescription: "Combine multiple images side by side or in a grid.",
    description: "Merge multiple images into one. Choose side-by-side, grid, or vertical layouts with custom spacing.",
    category: "image",
    icon: "LayoutGrid",
    tags: ["combine", "merge", "collage", "layout"],
    usageCount: 340_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 50,
    maxFiles: 20,
  },
  {
    id: "image-profile-photo",
    slug: "profile-photo",
    name: "Profile Photo Maker",
    shortDescription: "Create the perfect profile photo for social media.",
    description: "Crop, resize, and optimize photos for LinkedIn, Instagram, Twitter, and other platforms.",
    category: "image",
    icon: "UserCircle",
    tags: ["profile photo", "avatar", "social media", "crop"],
    usageCount: 520_000,
    estimatedTime: "~1s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 5,
  },
  {
    id: "image-remove-watermark",
    slug: "remove-watermark",
    name: "Remove Watermark",
    shortDescription: "Remove watermarks from images with AI.",
    description: "Automatically detect and remove watermarks, logos, and text overlays from images using AI inpainting.",
    category: "image",
    icon: "Stamp",
    tags: ["watermark", "remove", "clean", "AI"],
    usageCount: 470_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 5,
  },
  {
    id: "image-collage",
    slug: "collage",
    name: "Collage Maker",
    shortDescription: "Create beautiful photo collages with templates.",
    description: "Create stunning photo collages using beautiful templates. Drag and arrange photos with custom backgrounds.",
    category: "image",
    icon: "LayoutTemplate",
    tags: ["collage", "photo grid", "template", "arrange"],
    isFeatured: true,
    usageCount: 830_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 100,
    maxFiles: 20,
  },

  // ── Manual / Interactive Image Tools ─────────
  {
    id: "image-draw",
    slug: "draw",
    name: "Draw on Image",
    shortDescription: "Draw, annotate, and paint directly on your photos.",
    description: "Freehand draw on any image with a brush tool. Choose colors, brush size, and use an eraser. Perfect for annotations, highlights, and creative edits.",
    category: "image",
    icon: "Pen",
    tags: ["draw", "annotate", "paint", "brush", "doodle"],
    isNew: true,
    usageCount: 310_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-adjust",
    slug: "adjust",
    name: "Adjust Image",
    shortDescription: "Manually adjust brightness, contrast, and saturation.",
    description: "Fine-tune your photos with real-time sliders for brightness, contrast, and saturation. See a live preview as you adjust, then apply and download.",
    category: "image",
    icon: "SlidersHorizontal",
    tags: ["adjust", "brightness", "contrast", "saturation", "edit"],
    isNew: true,
    usageCount: 520_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "image-color-filter",
    slug: "color-filter",
    name: "Photo Filters",
    shortDescription: "Apply Instagram-style filters to your photos instantly.",
    description: "Apply stunning photo filters like Vivid, Warm, Cool, Vintage, Dramatic, and Fade. Preview in real-time and download the filtered image.",
    category: "image",
    icon: "Palette",
    tags: ["filter", "vintage", "vivid", "warm", "cool", "photo effects"],
    isNew: true,
    usageCount: 680_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    maxFileSizeMB: 25,
    maxFiles: 1,
  },
  {
    id: "ai-paraphrase",
    slug: "paraphrase",
    name: "AI Paraphraser",
    description: "Paraphrase any text in seconds. Reword sentences while keeping the original meaning. Ideal for avoiding plagiarism, simplifying academic writing, or refreshing old content.",
    shortDescription: "Reword text while keeping the original meaning.",
    category: "ai-writing",
    icon: "Repeat2",
    tags: ["paraphrase", "reword", "plagiarism", "rephrase", "writing"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 920_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your text", description: "Copy and paste any text you want to paraphrase — an essay, email, article, or paragraph." },
      { title: "Select paraphrase mode", description: "Choose between Standard, Fluency, Creative, Formal, or Shorten modes to control how the text is reworded." },
      { title: "Copy the result", description: "Get your paraphrased text instantly. Copy it or compare it side by side with the original." },
    ],
  },
  {
    id: "ai-script-writer",
    slug: "script-writer",
    name: "Script Writer",
    description: "Write professional scripts for YouTube videos, TikToks, podcasts, ads, and presentations. Enter your topic and style, and get a complete, engaging script in seconds.",
    shortDescription: "Write scripts for YouTube, TikTok, podcasts & ads.",
    category: "ai-writing",
    icon: "Film",
    tags: ["script", "youtube", "tiktok", "podcast", "video", "content creator"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 480_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Choose platform & topic", description: "Select YouTube, TikTok, Podcast, Ad, or Presentation. Then enter your video/episode topic." },
      { title: "Set style & length", description: "Choose tone (Educational, Entertaining, Informative) and target duration (30s, 1 min, 5 min, 10 min+)." },
      { title: "Download your script", description: "Get a fully structured script with intro, main points, and CTA. Copy or download as a text file." },
    ],
  },

  {
    id: "instagram-bio-generator",
    slug: "instagram-bio",
    name: "Instagram Bio Generator",
    description: "Generate the perfect Instagram bio based on your mood and personality. Choose from Happy, Mysterious, Professional, Funny, Romantic, Motivational, Aesthetic, Savage, and more emotions.",
    shortDescription: "Generate Instagram bios based on your mood.",
    category: "ai-writing",
    icon: "AtSign",
    tags: ["instagram", "bio", "profile", "mood", "social media", "personality"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 780_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Select your mood", description: "Pick the emotion or vibe that matches your personality — Happy, Mysterious, Professional, Funny, Romantic, Motivational, and more." },
      { title: "Add personal details", description: "Optionally add your name, profession, interests, or a tagline to make the bio uniquely yours." },
      { title: "Copy your perfect bio", description: "Get 5 bio variations instantly. Pick the one you love and copy it directly to your Instagram profile." },
    ],
  },
  {
    id: "description-writer",
    slug: "description",
    name: "Description Writer",
    description: "Write compelling descriptions for anything — products, YouTube videos, blog posts, Amazon listings, apps, real estate, events, and more. Powered by AI.",
    shortDescription: "Write descriptions for any product or content.",
    category: "ai-writing",
    icon: "FileText",
    tags: ["description", "product", "youtube", "amazon", "listing", "copywriting", "ai"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 560_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Choose what you're describing", description: "Select the type — product, video, blog post, app, service, event, or anything else you need described." },
      { title: "Enter key details", description: "Add a title, key features, target audience, and tone. The more details you give, the better the output." },
      { title: "Copy or download your description", description: "Get a polished, ready-to-use description in seconds. Copy it directly or export as a text file." },
    ],
  },

  // ── More AI Writing Tools ─────────────────────
  {
    id: "ai-blog-writer",
    slug: "blog-writer",
    name: "AI Blog Writer",
    description: "Generate full blog posts with AI. Input a topic and keywords, get a structured, SEO-optimized article in seconds.",
    shortDescription: "Generate full blog posts with AI.",
    category: "ai-writing",
    icon: "Newspaper",
    tags: ["blog", "article", "content", "SEO", "AI"],
    isNew: true,
    isFeatured: true,
    usageCount: 520_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-email-writer",
    slug: "email-writer",
    name: "AI Email Writer",
    description: "Write professional emails in seconds. Choose from cold outreach, follow-up, apology, thank you, and 20+ templates.",
    shortDescription: "Write professional emails with AI.",
    category: "ai-writing",
    icon: "Mail",
    tags: ["email", "professional", "outreach", "AI"],
    isNew: true,
    usageCount: 380_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-social-caption",
    slug: "social-caption",
    name: "Social Media Caption",
    description: "Generate engaging captions for Instagram, Twitter, LinkedIn, and TikTok. Includes hashtag suggestions.",
    shortDescription: "Generate social media captions with AI.",
    category: "ai-writing",
    icon: "MessageCircle",
    tags: ["social media", "caption", "instagram", "linkedin"],
    isNew: true,
    usageCount: 640_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "ai-headline-generator",
    slug: "headline",
    name: "Headline Generator",
    description: "Generate 10 compelling headline variations for any topic. Optimized for clicks, SEO, and social sharing.",
    shortDescription: "Generate compelling headlines with AI.",
    category: "ai-writing",
    icon: "Heading1",
    tags: ["headline", "title", "SEO", "clickbait"],
    usageCount: 290_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  // ── Converter ─────────────────────────────
  {
    id: "converter-json-formatter",
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data. Paste raw JSON to instantly beautify it with proper indentation, syntax highlighting, and error detection. Also supports JSON minification.",
    shortDescription: "Format, validate, and minify JSON instantly.",
    category: "converter",
    icon: "Braces",
    tags: ["json", "format", "validate", "minify", "developer", "api"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 680_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your JSON", description: "Copy and paste any JSON string, API response, or config file into the editor." },
      { title: "Format or minify", description: "Click Format to beautify with proper indentation, or Minify to compress for production use." },
      { title: "Copy the result", description: "Copy the formatted JSON to clipboard or download as a .json file." },
    ],
  },
  {
    id: "converter-base64",
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode plain text or files to Base64, or decode Base64 strings back to readable text. Useful for developers working with APIs, data URIs, and authentication tokens.",
    shortDescription: "Encode and decode Base64 strings instantly.",
    category: "converter",
    icon: "Hash",
    tags: ["base64", "encode", "decode", "developer", "api", "binary"],
    isNew: true,
    usageCount: 340_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter text or Base64", description: "Type or paste plain text to encode, or a Base64 string to decode." },
      { title: "Choose encode or decode", description: "Select whether you want to encode text to Base64 or decode Base64 back to plain text." },
      { title: "Copy the result", description: "Your encoded or decoded result appears instantly. Copy it with one click." },
    ],
  },

  // ── Video Downloader ──────────────────────────────
  {
    id: "video-downloader",
    slug: "downloader",
    name: "Video Downloader",
    description: "Download videos from YouTube, Instagram, Facebook, TikTok, Twitter/X, Pinterest, Vimeo, and 100+ other platforms. Paste the URL and choose your quality.",
    shortDescription: "Download videos from any social media platform.",
    category: "video",
    icon: "Download",
    tags: ["download", "youtube", "instagram", "tiktok", "facebook", "twitter", "social media"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_200_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste the video URL", description: "Copy the video URL from YouTube, Instagram, TikTok, Facebook, Twitter/X, or any other supported platform and paste it here." },
      { title: "Select quality & format", description: "Choose your preferred resolution (4K/1080p/720p/480p/360p) and format (MP4/WebM/MP3 for audio only)." },
      { title: "Download instantly", description: "Click Download and your video will be ready in seconds. No account needed, completely free." },
    ],
  },

  // ── Resume Tools ───────────────────────────────
  {
    id: "resume-builder",
    slug: "builder",
    name: "Resume Builder",
    description: "Create professional resumes with our easy-to-use builder. Fill in your details, choose a template, and download your resume in PDF or Word format.",
    shortDescription: "Build professional resumes with AI assistance.",
    category: "resume",
    icon: "FileEdit",
    tags: ["resume", "builder", "create", "pdf", "cv"],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    usageCount: 890_000,
    estimatedTime: "~5 min",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-analyzer",
    slug: "analyzer",
    name: "Resume Analyzer",
    description: "Upload your resume and get detailed AI-powered feedback. Fix common mistakes, improve formatting, and increase your chances of getting hired.",
    shortDescription: "Analyze resume and get improvement suggestions.",
    category: "resume",
    icon: "Search",
    tags: ["analyze", "review", "feedback", "ats score", "improve"],
    isPopular: true,
    isNew: true,
    usageCount: 420_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-skills-suggest",
    slug: "skills-suggest",
    name: "Skills Suggester",
    description: "Enter your job title or field and get personalized skill recommendations. Discover which skills employers are looking for in 2025.",
    shortDescription: "Get skill suggestions based on job title and industry.",
    category: "resume",
    icon: "Lightbulb",
    tags: ["skills", "suggestions", "keywords", "job search", "career"],
    isNew: true,
    usageCount: 310_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-cover-letter",
    slug: "cover-letter",
    name: "Cover Letter Generator",
    description: "Generate personalized cover letters in seconds. Input your details and the job description, get a tailored cover letter that matches your resume.",
    shortDescription: "Generate tailored cover letters for any job.",
    category: "resume",
    icon: "Mail",
    tags: ["cover letter", "application", "job", "generator", "ai"],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    usageCount: 580_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-formatter",
    slug: "formatter",
    name: "Resume Formatter",
    description: "Clean up and format your existing resume. Fix spacing, alignment, fonts, and structure to make it look professional and ATS-compliant.",
    shortDescription: "Format and clean up existing resumes.",
    category: "resume",
    icon: "AlignLeft",
    tags: ["format", "clean", "structure", "ats", "professional"],
    isNew: true,
    usageCount: 240_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-ats-checker",
    slug: "ats-checker",
    name: "ATS Score Checker",
    description: "Check how well your resume passes Applicant Tracking Systems. Upload your resume and paste a job description to get an ATS compatibility score with actionable fixes.",
    shortDescription: "Check your resume's ATS compatibility score.",
    category: "resume",
    icon: "ScanLine",
    tags: ["ats", "applicant tracking", "score", "job application", "keywords"],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    usageCount: 480_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-job-match",
    slug: "job-match",
    name: "Job Match Analyzer",
    description: "Compare your resume against a job description and get a match percentage. See exactly which skills and keywords you're missing to land the interview.",
    shortDescription: "Match your resume against any job description.",
    category: "resume",
    icon: "GitCompare",
    tags: ["job match", "job description", "keywords", "skills gap", "hiring"],
    isNew: true,
    usageCount: 350_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-summary",
    slug: "resume-summary",
    name: "Professional Summary Generator",
    description: "Generate a compelling professional summary for your resume in seconds. Enter your job title, years of experience, and key skills — get a polished 3-sentence summary instantly.",
    shortDescription: "Generate a compelling resume summary with AI.",
    category: "resume",
    icon: "Sparkles",
    tags: ["summary", "objective", "profile", "ai", "resume header"],
    isNew: true,
    isFeatured: true,
    usageCount: 390_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-linkedin",
    slug: "linkedin-writer",
    name: "LinkedIn Profile Writer",
    description: "Optimize your LinkedIn profile with AI. Generate a compelling headline, About section, and experience bullets that attract recruiters and rank higher in searches.",
    shortDescription: "Write an optimized LinkedIn profile with AI.",
    category: "resume",
    icon: "Linkedin",
    tags: ["linkedin", "profile", "headline", "about", "networking"],
    isNew: true,
    isFeatured: true,
    usageCount: 270_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "resume-interview-prep",
    slug: "interview-prep",
    name: "Interview Question Generator",
    description: "Upload your resume or enter your job title and get 20+ personalized interview questions with model answers. Prepare for behavioral, technical, and situational questions.",
    shortDescription: "Generate interview questions from your resume.",
    category: "resume",
    icon: "MessageSquare",
    tags: ["interview", "questions", "preparation", "behavioral", "hr"],
    isNew: true,
    usageCount: 310_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [".pdf", ".docx", ".doc"],
    maxFileSizeMB: 10,
    maxFiles: 1,
  },
  {
    id: "resume-keywords",
    slug: "keyword-optimizer",
    name: "Resume Keyword Optimizer",
    description: "Find and add the right keywords to your resume. Paste your resume and a job description to discover missing keywords, keyword density, and placement suggestions.",
    shortDescription: "Optimize resume keywords to beat ATS filters.",
    category: "resume",
    icon: "Tags",
    tags: ["keywords", "optimization", "ats", "search", "density"],
    isNew: true,
    usageCount: 220_000,
    estimatedTime: "~5s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── Resignation Letter ─────────────────────────
  {
    id: "resume-resignation",
    slug: "resignation-letter",
    name: "Resignation Letter Writer",
    description: "Write a professional resignation letter in seconds. Choose your tone, notice period, and reasons — get a polished letter ready to send to your employer.",
    shortDescription: "Write a professional resignation letter with AI.",
    category: "resume",
    icon: "FileX2",
    tags: ["resignation", "quit job", "letter", "notice period", "professional"],
    isNew: true,
    usageCount: 290_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter your details", description: "Add your name, company, manager, position, and last working day." },
      { title: "Choose your tone", description: "Select from Professional, Grateful, Formal, or Brief tone styles." },
      { title: "Copy your letter", description: "Get a complete, ready-to-send resignation letter." },
    ],
  },

  // ── More Video Tools ─────────────────────────
  {
    id: "video-trim",
    slug: "trim",
    name: "Trim Video",
    description: "Cut and trim videos to exact start and end points. Remove unwanted parts from the beginning, middle, or end of any video.",
    shortDescription: "Cut and trim videos to exact duration.",
    category: "video",
    icon: "Scissors",
    tags: ["trim", "cut", "clip", "shorten"],
    isPopular: true,
    usageCount: 860_000,
    estimatedTime: "~15s",
    acceptedFileTypes: [".mp4", ".mov", ".avi", ".webm", ".mkv"],
    maxFileSizeMB: 500,
    maxFiles: 1,
  },
  {
    id: "video-merge",
    slug: "merge",
    name: "Merge Videos",
    description: "Combine multiple video clips into one seamless video. Drag to reorder clips before merging.",
    shortDescription: "Combine multiple video clips into one.",
    category: "video",
    icon: "Combine",
    tags: ["merge", "combine", "join", "concatenate"],
    usageCount: 540_000,
    estimatedTime: "~30s",
    acceptedFileTypes: [".mp4", ".mov", ".avi", ".webm"],
    maxFileSizeMB: 500,
    maxFiles: 10,
  },
  {
    id: "video-convert",
    slug: "convert",
    name: "Convert Video",
    description: "Convert video files between all major formats including MP4, MOV, AVI, WebM, MKV, and FLV.",
    shortDescription: "Convert video to any format.",
    category: "video",
    icon: "ArrowRightLeft",
    tags: ["convert", "mp4", "mov", "avi", "webm", "format"],
    usageCount: 720_000,
    estimatedTime: "~20s",
    acceptedFileTypes: [".mp4", ".mov", ".avi", ".webm", ".mkv", ".flv", ".wmv"],
    maxFileSizeMB: 500,
    maxFiles: 5,
  },
  {
    id: "video-to-mp3",
    slug: "to-mp3",
    name: "Video to MP3",
    description: "Extract audio from any video file and download as high-quality MP3. Supports MP4, MOV, AVI, WebM.",
    shortDescription: "Extract audio from video as MP3.",
    category: "video",
    icon: "Music",
    tags: ["audio", "mp3", "extract", "music"],
    isPopular: true,
    isFeatured: true,
    usageCount: 980_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".mp4", ".mov", ".avi", ".webm", ".mkv"],
    maxFileSizeMB: 500,
    maxFiles: 5,
  },
  {
    id: "video-to-gif",
    slug: "video-to-gif",
    name: "Video to GIF",
    description: "Convert a short video clip into an animated GIF. Choose frame rate and size for the perfect loop.",
    shortDescription: "Convert video clips to animated GIFs.",
    category: "video",
    icon: "PlayCircle",
    tags: ["gif", "animated", "loop", "meme"],
    isNew: true,
    isFeatured: true,
    usageCount: 640_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".mp4", ".mov", ".webm", ".gif"],
    maxFileSizeMB: 100,
    maxFiles: 1,
  },
  {
    id: "video-speed",
    slug: "speed",
    name: "Change Video Speed",
    description: "Speed up or slow down any video. Create time-lapses or slow-motion effects with speeds from 0.25x to 4x.",
    shortDescription: "Speed up or slow down videos.",
    category: "video",
    icon: "FastForward",
    tags: ["speed", "slow motion", "timelapse", "fast forward"],
    isNew: true,
    usageCount: 380_000,
    estimatedTime: "~20s",
    acceptedFileTypes: [".mp4", ".mov", ".avi", ".webm"],
    maxFileSizeMB: 500,
    maxFiles: 1,
  },
  {
    id: "video-mute",
    slug: "mute",
    name: "Mute Video",
    description: "Remove or mute the audio track from any video file. Download a silent video for background use or adding new audio.",
    shortDescription: "Remove audio track from video.",
    category: "video",
    icon: "VolumeX",
    tags: ["mute", "remove audio", "silent", "no sound"],
    usageCount: 290_000,
    estimatedTime: "~10s",
    acceptedFileTypes: [".mp4", ".mov", ".avi", ".webm", ".mkv"],
    maxFileSizeMB: 500,
    maxFiles: 5,
  },

  // ── More Converter Tools ──────────────────────
  {
    id: "converter-url",
    slug: "url-encode",
    name: "URL Encoder / Decoder",
    description: "Encode and decode URLs and query strings. Convert special characters to percent-encoded format or back to readable text. Essential for web developers.",
    shortDescription: "Encode and decode URLs instantly.",
    category: "converter",
    icon: "Link2",
    tags: ["url", "encode", "decode", "percent encoding", "uri", "developer"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 520_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your URL or text", description: "Enter any URL, query string, or text that needs to be encoded or decoded." },
      { title: "Choose encode or decode", description: "Encode converts special characters to %XX format. Decode converts %XX back to readable characters." },
      { title: "Copy the result", description: "Your encoded or decoded URL is ready instantly. Copy it to clipboard with one click." },
    ],
  },
  {
    id: "converter-word-count",
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, paragraphs, and reading time. Analyze text density instantly. Paste any text to see detailed stats.",
    shortDescription: "Count words, characters, and reading time.",
    category: "converter",
    icon: "Type",
    tags: ["word count", "character count", "reading time", "text analysis", "writer"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 890_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your text", description: "Copy and paste any text — an essay, article, email, or document." },
      { title: "See instant stats", description: "Get word count, character count (with/without spaces), sentence count, paragraph count, and estimated reading time." },
      { title: "Check keyword density", description: "See the top keywords and their frequency to check for repetition." },
    ],
  },
  {
    id: "converter-password",
    slug: "password-gen",
    name: "Password Generator",
    description: "Generate strong, secure random passwords. Customize length, include uppercase, lowercase, numbers, and special characters. Check password strength instantly.",
    shortDescription: "Generate strong random passwords instantly.",
    category: "converter",
    icon: "KeyRound",
    tags: ["password", "generator", "security", "random", "strong password"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_100_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Set your requirements", description: "Choose password length and which character types to include: uppercase, lowercase, numbers, and symbols." },
      { title: "Generate instantly", description: "Click Generate to create a cryptographically secure random password." },
      { title: "Copy & use", description: "Copy your new password to clipboard with one click. Generate as many as you need." },
    ],
  },
  {
    id: "converter-color",
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, and HSL formats instantly. Pick colors visually, see live previews, and copy values for CSS or design tools.",
    shortDescription: "Convert colors between HEX, RGB, HSL formats.",
    category: "converter",
    icon: "Pipette",
    tags: ["color", "hex", "rgb", "hsl", "design", "css"],
    isNew: true,
    isFeatured: true,
    usageCount: 430_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter a color value", description: "Type a HEX code (#ff5733), RGB (255, 87, 51), or HSL value. Or use the color picker." },
      { title: "See all formats", description: "Get the color in HEX, RGB, and HSL formats simultaneously with a live preview." },
      { title: "Copy any format", description: "Copy the color value in whichever format you need for CSS or design tools." },
    ],
  },
  {
    id: "converter-csv-json",
    slug: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV files or pasted CSV data to JSON format. Supports custom delimiters and headers. Perfect for data transformation and API work.",
    shortDescription: "Convert CSV data to JSON format.",
    category: "converter",
    icon: "Table2",
    tags: ["csv", "json", "convert", "data", "api", "developer"],
    isNew: true,
    usageCount: 360_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your CSV data", description: "Copy and paste CSV data with or without headers. Supports comma, semicolon, or tab delimiters." },
      { title: "Convert to JSON", description: "Click Convert to transform your CSV into a clean JSON array." },
      { title: "Copy or download", description: "Copy the JSON to clipboard or download it as a .json file." },
    ],
  },
  {
    id: "converter-html-markdown",
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML code to clean Markdown format. Paste HTML from any website or document and get clean .md output. Also supports Markdown to HTML.",
    shortDescription: "Convert HTML to Markdown and vice versa.",
    category: "converter",
    icon: "FileCode2",
    tags: ["html", "markdown", "convert", "documentation", "developer"],
    isNew: true,
    usageCount: 280_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-markdown",
    slug: "markdown",
    name: "Markdown Editor",
    description: "Write Markdown with a live HTML preview side by side. Supports GitHub Flavored Markdown. Copy the rendered HTML or export the .md file.",
    shortDescription: "Write Markdown with live HTML preview.",
    category: "converter",
    icon: "Notebook",
    tags: ["markdown", "preview", "editor", "documentation", "readme"],
    isNew: true,
    usageCount: 320_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── Ad Copy ──────────────────────────────────
  {
    id: "ai-ad-copy",
    slug: "ad-copy",
    name: "AI Ad Copy Writer",
    description: "Generate high-converting ad copy for Google Ads, Facebook Ads, Instagram, and more. Enter your product and get headlines, descriptions, and CTAs optimized for conversions.",
    shortDescription: "Generate high-converting ad copy with AI.",
    category: "ai-writing",
    icon: "Megaphone",
    tags: ["ad copy", "advertising", "google ads", "facebook ads", "marketing", "copywriting"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 410_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Describe your product", description: "Enter your product name, key benefits, target audience, and the platform you're advertising on." },
      { title: "Choose format & tone", description: "Select headline count, description length, and tone (persuasive, urgent, friendly, professional)." },
      { title: "Copy your ad copy", description: "Get multiple variations of headlines and descriptions for A/B testing in your campaigns." },
    ],
  },

  // ── Calculator Tools ─────────────────────────
  {
    id: "calc-age",
    slug: "age",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, and days from any date of birth. Also shows next birthday countdown and total days lived.",
    shortDescription: "Calculate exact age from date of birth.",
    category: "calculator",
    icon: "Cake",
    tags: ["age", "birthday", "date of birth", "years", "months"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_800_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-bmi",
    slug: "bmi",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index (BMI) with height and weight. Supports metric (kg/cm) and imperial (lbs/ft) units. Shows BMI category and healthy weight range.",
    shortDescription: "Calculate BMI with height and weight.",
    category: "calculator",
    icon: "Activity",
    tags: ["bmi", "body mass index", "health", "weight", "fitness"],
    isPopular: true,
    isFeatured: true,
    usageCount: 1_900_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-percentage",
    slug: "percentage",
    name: "Percentage Calculator",
    description: "Calculate percentages instantly. Find what % one number is of another, calculate % increase/decrease, or find the original value from a percentage.",
    shortDescription: "Calculate any percentage instantly.",
    category: "calculator",
    icon: "Percent",
    tags: ["percentage", "percent", "discount", "increase", "decrease", "math"],
    isPopular: true,
    isFeatured: true,
    usageCount: 3_400_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-emi",
    slug: "emi",
    name: "EMI Calculator",
    description: "Calculate monthly loan EMI for home loans, car loans, and personal loans. Shows full amortization schedule with principal and interest breakdown.",
    shortDescription: "Calculate monthly loan EMI instantly.",
    category: "calculator",
    icon: "Landmark",
    tags: ["emi", "loan", "interest", "home loan", "car loan", "mortgage"],
    isPopular: true,
    isFeatured: true,
    usageCount: 2_100_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-tip",
    slug: "tip",
    name: "Tip Calculator",
    description: "Calculate restaurant tip and split bills among friends. Enter bill amount, tip percentage, and number of people to get per-person amounts instantly.",
    shortDescription: "Calculate tip and split bills easily.",
    category: "calculator",
    icon: "Receipt",
    tags: ["tip", "restaurant", "bill split", "split", "gratuity"],
    usageCount: 980_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-discount",
    slug: "discount",
    name: "Discount Calculator",
    description: "Calculate sale price after discount, find discount percentage, or work backwards from a discounted price. Perfect for shopping and pricing.",
    shortDescription: "Calculate discounts and sale prices.",
    category: "calculator",
    icon: "Tag",
    tags: ["discount", "sale", "price", "coupon", "savings", "shopping"],
    isPopular: true,
    usageCount: 1_600_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "calc-date",
    slug: "date-diff",
    name: "Date Calculator",
    description: "Calculate the difference between two dates in days, weeks, months, and years. Add or subtract days from a date. Find what day of the week any date falls on.",
    shortDescription: "Calculate date differences and add/subtract days.",
    category: "calculator",
    icon: "CalendarDays",
    tags: ["date", "days between", "date difference", "calendar", "deadline"],
    usageCount: 1_200_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── More Converter Utility Tools ──────────────
  {
    id: "converter-case",
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case. Process any amount of text instantly.",
    shortDescription: "Convert text between all case formats.",
    category: "converter",
    icon: "CaseSensitive",
    tags: ["case", "uppercase", "lowercase", "camelCase", "title case", "snake_case", "developer"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_800_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Paste your text", description: "Enter any text that needs to be converted to a different case format." },
      { title: "Choose your case", description: "Select from UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, or kebab-case." },
      { title: "Copy the result", description: "Your converted text appears instantly. Copy it with one click." },
    ],
  },
  {
    id: "converter-lorem",
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder Lorem Ipsum text for designs and mockups. Choose number of words, sentences, or paragraphs. Includes classic and modern variations.",
    shortDescription: "Generate placeholder text for designs.",
    category: "converter",
    icon: "AlignLeft",
    tags: ["lorem ipsum", "placeholder", "dummy text", "design", "mockup", "developer"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_400_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-number-base",
    slug: "number-converter",
    name: "Number Base Converter",
    description: "Convert numbers between decimal, binary, hexadecimal, and octal. Instantly see the same number in all four bases side by side.",
    shortDescription: "Convert numbers between decimal, binary, hex, and octal.",
    category: "converter",
    icon: "Hash",
    tags: ["binary", "hex", "decimal", "octal", "base", "developer", "convert"],
    isNew: true,
    usageCount: 580_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-uuid",
    slug: "uuid-gen",
    name: "UUID Generator",
    description: "Generate version 4 UUID (Universally Unique Identifier) instantly. Generate single or bulk UUIDs. Perfect for database IDs and development.",
    shortDescription: "Generate UUID/GUID instantly.",
    category: "converter",
    icon: "Fingerprint",
    tags: ["uuid", "guid", "unique id", "identifier", "developer", "database"],
    isNew: true,
    isFeatured: true,
    usageCount: 760_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-text-reverse",
    slug: "text-reverser",
    name: "Text Reverser",
    description: "Reverse any text instantly. Reverse entire string, reverse word order, or reverse each word individually. Also supports upside-down text.",
    shortDescription: "Reverse text, words, or sentences.",
    category: "converter",
    icon: "Undo2",
    tags: ["reverse", "text", "flip", "mirror", "backwards"],
    usageCount: 420_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-random-number",
    slug: "random-number",
    name: "Random Number Generator",
    description: "Generate random numbers in any range. Generate single numbers, lists, dice rolls, lottery numbers, or coin flips. Set custom min/max values.",
    shortDescription: "Generate random numbers in any range.",
    category: "converter",
    icon: "Dice5",
    tags: ["random", "number", "dice", "lottery", "generate", "range"],
    usageCount: 890_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },
  {
    id: "converter-dedupe",
    slug: "remove-duplicates",
    name: "Remove Duplicate Lines",
    description: "Remove duplicate lines from any text. Sort lines alphabetically, count duplicates, and keep only unique lines. Perfect for cleaning up data and lists.",
    shortDescription: "Remove duplicate lines from text instantly.",
    category: "converter",
    icon: "ListFilter",
    tags: ["duplicate", "remove", "unique", "lines", "sort", "clean", "list"],
    usageCount: 340_000,
    estimatedTime: "~instant",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
  },

  // ── More AI Writing Tools ─────────────────────
  {
    id: "ai-hashtag",
    slug: "hashtag-gen",
    name: "AI Hashtag Generator",
    description: "Generate trending hashtags for Instagram, TikTok, Twitter, and LinkedIn. Enter your topic or upload an image to get 30+ relevant hashtags sorted by popularity.",
    shortDescription: "Generate trending hashtags for social media.",
    category: "ai-writing",
    icon: "Hash",
    tags: ["hashtag", "instagram", "tiktok", "twitter", "social media", "trending"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 1_300_000,
    estimatedTime: "~2s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Enter your topic", description: "Type your post topic, niche, or content description." },
      { title: "Select platform", description: "Choose Instagram, TikTok, Twitter/X, or LinkedIn for platform-optimized hashtags." },
      { title: "Copy hashtags", description: "Get 30+ relevant hashtags sorted by reach. Copy all or select individual hashtags." },
    ],
  },
  {
    id: "ai-story",
    slug: "story-generator",
    name: "AI Story Generator",
    description: "Generate short stories, creative fiction, or narrative content with AI. Set the genre, characters, setting, and length — get a complete story in seconds.",
    shortDescription: "Generate creative stories with AI.",
    category: "ai-writing",
    icon: "BookOpen",
    tags: ["story", "creative writing", "fiction", "narrative", "short story", "ai"],
    isNew: true,
    isFeatured: true,
    usageCount: 640_000,
    estimatedTime: "~8s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Set the scene", description: "Choose genre (romance, thriller, comedy, fantasy etc.), describe characters, and set the scene." },
      { title: "Choose length", description: "Select flash fiction (100 words), short story (500 words), or extended story (1000+ words)." },
      { title: "Get your story", description: "AI generates a complete story with beginning, middle, and end. Edit, copy, or regenerate." },
    ],
  },
  {
    id: "ai-business-name",
    slug: "business-name",
    name: "Business Name Generator",
    description: "Generate creative and catchy business names for your startup or brand. Enter keywords describing your business and get 20+ unique name ideas with domain availability hints.",
    shortDescription: "Generate creative business names with AI.",
    category: "ai-writing",
    icon: "Building2",
    tags: ["business name", "brand name", "startup", "company name", "domain", "branding"],
    isNew: true,
    isFeatured: true,
    isPopular: true,
    usageCount: 720_000,
    estimatedTime: "~3s",
    acceptedFileTypes: [],
    maxFileSizeMB: 0,
    maxFiles: 0,
    howItWorks: [
      { title: "Describe your business", description: "Enter keywords about your business type, industry, values, and target audience." },
      { title: "Choose name style", description: "Pick from Creative, Professional, Catchy, Technical, or Minimal name styles." },
      { title: "Pick your name", description: "Get 20+ unique business name suggestions. Short, memorable, and brandable." },
    ],
  },
];

// ─────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────

export function getToolBySlug(slug: string, category: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug && t.category === category);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getFeaturedTools(limit = 8): Tool[] {
  return TOOLS.filter((t) => t.isFeatured)
    .sort((a, b) => (b.usageCount ?? 0) - (a.usageCount ?? 0))
    .slice(0, limit);
}

export function getPopularTools(limit = 12): Tool[] {
  return TOOLS.filter((t) => t.isPopular)
    .sort((a, b) => (b.usageCount ?? 0) - (a.usageCount ?? 0))
    .slice(0, limit);
}

export { TOOL_CATEGORIES } from "@/config/navigation";
